/* =============================================================
   Kitchen Mix — Seed Session 3 : Cookeo + Cuiseur riz + Cuiseur vapeur
   -------------------------------------------------------------
   30 recettes nouvelles (10 par appareil), aucun doublon de slug.

   Pour activer : ajouter dans scripts/seed-mega.ts :
     import { SEED_SESSION_3 } from "../lib/seed-session-3-rapide";
     ...puis dans ALL_RECIPES, ajouter ...SEED_SESSION_3
   ============================================================= */

import type { SeedRecette } from "./seed-data";

export const SEED_SESSION_3: SeedRecette[] = [

  // ═══════════════════════════════════════════════════════════
  //                       COOKEO (10)
  // ═══════════════════════════════════════════════════════════

  {
    slug: "blanquette-veau-cookeo",
    titre: "Blanquette de veau express",
    description: "La blanquette de veau traditionnelle française, version Cookeo en 30 minutes au lieu de 2 heures. Sauce onctueuse à souhait.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 30,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["COOKEO"],
    categories: ["plat"],
    regime: [],
    tags: ["blanquette", "veau", "français", "mijoté"],
    calories_par_portion: 420,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Sauté de veau (épaule)", quantite: 800, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Carottes", quantite: 3, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Poireaux", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Oignon", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Champignons de Paris", quantite: 250, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Bouillon de volaille", quantite: 500, unite: "ml", categorie: "Épicerie" },
      { nom: "Crème fraîche", quantite: 200, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Jaune d'œuf", quantite: 1, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Beurre", quantite: 30, unite: "g", categorie: "Produits laitiers" },
      { nom: "Farine", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Bouquet garni", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Citron", quantite: 0.5, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mode Dorer : faire revenir le veau en cubes avec le beurre 5 minutes. Saupoudrer de farine, mélanger." },
      { numero: 2, instruction: "Ajouter oignon émincé, carottes en rondelles, poireaux émincés, bouquet garni et bouillon." },
      { numero: 3, instruction: "Programme Cuisson sous pression 25 minutes.", duree: 1500 },
      { numero: 4, instruction: "Relâcher la pression. Ajouter les champignons coupés en 4. Mode Mijotage 5 minutes.", duree: 300 },
      { numero: 5, instruction: "Hors cuisson, mélanger crème, jaune d'œuf et jus de citron. Verser dans le Cookeo en remuant.", conseil: "Ne pas faire bouillir après l'ajout du jaune d'œuf. Servir avec du riz." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "navarin-agneau-cookeo",
    titre: "Navarin d'agneau printanier",
    description: "Le navarin d'agneau aux légumes nouveaux, mijoté express au Cookeo. Saveurs printanières en moins d'1 heure.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 20,
    temps_cuisson: 35,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["COOKEO"],
    categories: ["plat"],
    regime: ["sans-lactose"],
    tags: ["navarin", "agneau", "printemps", "mijoté"],
    calories_par_portion: 480,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Sauté d'agneau (épaule)", quantite: 800, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Carottes nouvelles", quantite: 400, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Navets nouveaux", quantite: 400, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Petits pois frais", quantite: 200, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Pommes de terre nouvelles", quantite: 400, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Oignons grelots", quantite: 200, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Concentré de tomate", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Bouillon de volaille", quantite: 500, unite: "ml", categorie: "Épicerie" },
      { nom: "Vin blanc sec", quantite: 200, unite: "ml", categorie: "Boissons" },
      { nom: "Ail", quantite: 3, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Bouquet garni", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Farine", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Huile d'olive", quantite: 30, unite: "ml", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mode Dorer : faire colorer l'agneau dans l'huile 8 minutes. Saupoudrer de farine, mélanger 1 minute." },
      { numero: 2, instruction: "Ajouter ail haché, concentré de tomate, vin blanc, bouillon, bouquet garni." },
      { numero: 3, instruction: "Programme Cuisson sous pression 20 minutes.", duree: 1200 },
      { numero: 4, instruction: "Ajouter carottes, navets, pommes de terre, oignons grelots. Programme 10 minutes.", duree: 600 },
      { numero: 5, instruction: "Relâcher la pression. Ajouter les petits pois. Mode Mijotage 3 minutes.", duree: 180 },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "soupe-poisson-rouille-cookeo",
    titre: "Soupe de poisson à la rouille",
    description: "La soupe de poisson provençale crémeuse, servie avec sa rouille à l'ail et croûtons. Idéal pour utiliser les arêtes.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 30,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["COOKEO"],
    categories: ["soupe", "entree"],
    regime: ["sans-lactose"],
    tags: ["soupe poisson", "provençal", "rouille", "Méditerranée"],
    calories_par_portion: 280,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Poissons de roche (rougets, vives)", quantite: 1000, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Tomates", quantite: 4, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Oignon", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Poireau", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Fenouil", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Ail", quantite: 4, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Pistils de safran", quantite: 0.3, unite: "g", categorie: "Condiments" },
      { nom: "Concentré de tomate", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Pastis", quantite: 30, unite: "ml", categorie: "Boissons" },
      { nom: "Eau", quantite: 1500, unite: "ml", categorie: "Autre" },
      { nom: "Huile d'olive", quantite: 50, unite: "ml", categorie: "Condiments" },
      { nom: "Croûtons", quantite: 100, unite: "g", categorie: "Boulangerie" },
      { nom: "Mayonnaise", quantite: 100, unite: "g", categorie: "Condiments" },
      { nom: "Piment d'Espelette", quantite: 2, unite: "g", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mode Dorer : faire suer oignons, poireau et fenouil émincés dans l'huile 5 min." },
      { numero: 2, instruction: "Ajouter ail, tomates concassées, concentré, safran, pastis et poissons (entiers, vidés). Verser l'eau." },
      { numero: 3, instruction: "Programme Cuisson sous pression 25 minutes.", duree: 1500 },
      { numero: 4, instruction: "Passer le tout au moulin à légumes (grille fine), puis au chinois pour retirer arêtes et peaux.", conseil: "Étape clé pour une vraie soupe de pêcheur." },
      { numero: 5, instruction: "Préparer la rouille : mélanger mayonnaise, 2 gousses d'ail écrasées et piment d'Espelette. Servir la soupe avec croûtons et rouille." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "osso-buco-milanese-cookeo",
    titre: "Osso buco à la milanaise",
    description: "Le grand classique italien : jarret de veau braisé à la tomate et au vin blanc, parfumé à la gremolata.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 20,
    temps_cuisson: 50,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["COOKEO"],
    categories: ["plat"],
    regime: ["sans-lactose"],
    tags: ["osso buco", "italien", "veau", "milanais"],
    calories_par_portion: 480,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Tranches de jarret de veau", quantite: 4, unite: "pièce", categorie: "Viandes & Poissons" },
      { nom: "Carottes", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Céleri branche", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Oignon", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Tomates concassées", quantite: 400, unite: "g", categorie: "Épicerie" },
      { nom: "Vin blanc sec", quantite: 250, unite: "ml", categorie: "Boissons" },
      { nom: "Bouillon de bœuf", quantite: 250, unite: "ml", categorie: "Épicerie" },
      { nom: "Farine", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Huile d'olive", quantite: 30, unite: "ml", categorie: "Condiments" },
      { nom: "Citron jaune (zeste)", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Persil plat", quantite: 20, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Ail", quantite: 3, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Romarin", quantite: 5, unite: "g", categorie: "Fruits & Légumes" },
    ],
    etapes: [
      { numero: 1, instruction: "Fariner les tranches de jarret. Mode Dorer : les faire colorer dans l'huile 5 min de chaque côté." },
      { numero: 2, instruction: "Réserver la viande. Faire suer oignon, carottes et céleri en dés (mirepoix) dans le même Cookeo 5 min." },
      { numero: 3, instruction: "Remettre la viande, ajouter tomates, vin, bouillon et romarin." },
      { numero: 4, instruction: "Programme Cuisson sous pression 50 minutes.", duree: 3000 },
      { numero: 5, instruction: "Préparer la gremolata : hacher persil, ail et zeste de citron. Saupoudrer sur l'osso buco au moment de servir.", conseil: "Servir avec un risotto safrané ou polenta crémeuse." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "soupe-thai-tom-kha-cookeo",
    titre: "Soupe thaï Tom Kha Gai",
    description: "La célèbre soupe thaïlandaise au lait de coco, citronnelle et galanga. Parfumée et réconfortante en 25 minutes.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 20,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["COOKEO"],
    categories: ["soupe", "plat"],
    regime: ["sans-gluten", "sans-lactose"],
    tags: ["tom kha", "thaï", "lait coco", "citronnelle"],
    calories_par_portion: 320,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Blancs de poulet", quantite: 400, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Lait de coco", quantite: 800, unite: "ml", categorie: "Épicerie" },
      { nom: "Bouillon de volaille", quantite: 400, unite: "ml", categorie: "Épicerie" },
      { nom: "Champignons de Paris ou shiitakes", quantite: 200, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Citronnelle", quantite: 3, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Galanga ou gingembre frais", quantite: 30, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Feuilles de combava", quantite: 4, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Sauce poisson (nuoc-mâm)", quantite: 30, unite: "ml", categorie: "Condiments" },
      { nom: "Pâte de curry rouge thaï", quantite: 20, unite: "g", categorie: "Condiments" },
      { nom: "Citrons verts", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Coriandre fraîche", quantite: 15, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Piment thaï", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Sucre de palme", quantite: 10, unite: "g", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Écraser la citronnelle au plat du couteau. Couper le galanga en rondelles." },
      { numero: 2, instruction: "Mode Dorer : faire revenir la pâte de curry 1 min. Ajouter bouillon, lait de coco, citronnelle, galanga, feuilles de combava." },
      { numero: 3, instruction: "Ajouter le poulet en lanières, champignons, sauce poisson et sucre. Programme Cuisson rapide 12 minutes.", duree: 720 },
      { numero: 4, instruction: "Hors feu, ajouter le jus des citrons verts. Servir parsemé de coriandre et piment émincé.", conseil: "Retirer citronnelle, galanga et combava avant de servir." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "pates-bolognaise-cookeo",
    titre: "Pâtes bolognaise tout-en-un",
    description: "Spaghettis et sauce bolognaise cuits ensemble dans le Cookeo en 15 minutes. Repas familial express.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 15,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["COOKEO"],
    categories: ["plat"],
    regime: [],
    tags: ["pâtes", "bolognaise", "famille", "rapide"],
    calories_par_portion: 520,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Spaghettis", quantite: 350, unite: "g", categorie: "Épicerie" },
      { nom: "Bœuf haché", quantite: 400, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Tomates concassées", quantite: 400, unite: "g", categorie: "Épicerie" },
      { nom: "Oignon", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Carotte", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Ail", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Bouillon de bœuf", quantite: 700, unite: "ml", categorie: "Épicerie" },
      { nom: "Origan séché", quantite: 5, unite: "g", categorie: "Condiments" },
      { nom: "Concentré de tomate", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Huile d'olive", quantite: 20, unite: "ml", categorie: "Condiments" },
      { nom: "Parmesan râpé", quantite: 50, unite: "g", categorie: "Produits laitiers" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mode Dorer : faire revenir oignon haché, ail et carotte râpée dans l'huile 3 minutes." },
      { numero: 2, instruction: "Ajouter le bœuf haché, faire colorer 5 minutes en l'émiettant." },
      { numero: 3, instruction: "Ajouter tomates concassées, concentré, origan, sel. Casser les spaghettis en deux par-dessus, sans mélanger. Verser le bouillon pour couvrir." },
      { numero: 4, instruction: "Programme Cuisson rapide 7 minutes.", duree: 420 },
      { numero: 5, instruction: "Mélanger, parsemer de parmesan.", conseil: "Si la sauce est trop liquide, mode Dorer 2 min pour réduire." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "pot-au-feu-cookeo",
    titre: "Pot-au-feu express",
    description: "Le pot-au-feu traditionnel français en 1 heure au Cookeo au lieu de 4. Bouillon parfumé et viandes fondantes.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 20,
    temps_cuisson: 60,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["COOKEO"],
    categories: ["plat", "soupe"],
    regime: ["sans-gluten", "sans-lactose"],
    tags: ["pot-au-feu", "français", "traditionnel", "mijoté"],
    calories_par_portion: 440,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Plat de côtes", quantite: 600, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Paleron", quantite: 500, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Os à moelle", quantite: 4, unite: "pièce", categorie: "Viandes & Poissons" },
      { nom: "Carottes", quantite: 6, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Poireaux", quantite: 3, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Navets", quantite: 4, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Pommes de terre", quantite: 4, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Céleri branche", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Oignon", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Clous de girofle", quantite: 3, unite: "pièce", categorie: "Condiments" },
      { nom: "Bouquet garni", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Gros sel", quantite: 15, unite: "g", categorie: "Condiments" },
      { nom: "Poivre en grains", quantite: 5, unite: "g", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Piquer l'oignon des clous de girofle. Mettre les viandes, oignon, bouquet garni, sel et poivre dans le Cookeo. Couvrir d'eau." },
      { numero: 2, instruction: "Programme Cuisson sous pression 45 minutes.", duree: 2700 },
      { numero: 3, instruction: "Relâcher la pression. Écumer. Ajouter carottes, poireaux, navets, céleri en tronçons et pommes de terre." },
      { numero: 4, instruction: "Programme 12 minutes.", duree: 720 },
      { numero: 5, instruction: "Ajouter les os à moelle 3 min avant la fin. Servir avec gros sel, moutarde et cornichons." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "moules-mariniere-cookeo",
    titre: "Moules marinière au vin blanc",
    description: "Les moules marinière classiques en 5 minutes au Cookeo. Servies avec leur jus parfumé au persil.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 5,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["COOKEO"],
    categories: ["plat", "entree"],
    regime: ["sans-gluten"],
    tags: ["moules", "marinière", "fruits de mer", "rapide"],
    calories_par_portion: 280,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Moules de bouchot", quantite: 2000, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Échalotes", quantite: 4, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Vin blanc sec (Muscadet)", quantite: 250, unite: "ml", categorie: "Boissons" },
      { nom: "Beurre", quantite: 50, unite: "g", categorie: "Produits laitiers" },
      { nom: "Persil plat", quantite: 30, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Ail", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Poivre", quantite: 1, unite: "pincée", categorie: "Condiments" },
      { nom: "Crème fraîche (optionnelle)", quantite: 100, unite: "ml", categorie: "Produits laitiers" },
    ],
    etapes: [
      { numero: 1, instruction: "Nettoyer les moules : gratter, ébarber, jeter celles qui restent ouvertes." },
      { numero: 2, instruction: "Mode Dorer : faire fondre le beurre, ajouter échalotes et ail hachés. Suer 2 min." },
      { numero: 3, instruction: "Ajouter les moules, le vin blanc et le poivre. Fermer le couvercle." },
      { numero: 4, instruction: "Programme Cuisson rapide 4 minutes.", duree: 240, conseil: "Les moules doivent être toutes ouvertes. Jeter les fermées." },
      { numero: 5, instruction: "Ajouter le persil ciselé et la crème (version normande). Servir immédiatement avec des frites." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "compotee-pommes-cookeo",
    titre: "Compote de pommes maison",
    description: "Une compote de pommes maison en 10 minutes au Cookeo. Sans sucre ajouté ni conservateurs.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 10,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["COOKEO"],
    categories: ["dessert", "petit-dejeuner"],
    regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["compote", "pommes", "dessert", "rapide"],
    calories_par_portion: 95,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Pommes (Gala ou Golden)", quantite: 1000, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Eau", quantite: 100, unite: "ml", categorie: "Autre" },
      { nom: "Cannelle", quantite: 2, unite: "g", categorie: "Condiments" },
      { nom: "Vanille", quantite: 5, unite: "ml", categorie: "Épicerie" },
      { nom: "Citron", quantite: 0.5, unite: "pièce", categorie: "Fruits & Légumes" },
    ],
    etapes: [
      { numero: 1, instruction: "Éplucher, épépiner et couper les pommes en cubes." },
      { numero: 2, instruction: "Mettre dans le Cookeo avec eau, cannelle, vanille et jus de citron." },
      { numero: 3, instruction: "Programme Cuisson rapide 5 minutes.", duree: 300 },
      { numero: 4, instruction: "Écraser à la fourchette pour une compote rustique, ou mixer pour une texture lisse.", conseil: "Conservation 5 jours au frigo, ou en pots stérilisés à chaud pour 6 mois." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "sauce-tomate-conserve-cookeo",
    titre: "Sauce tomate maison à conserver",
    description: "Une sauce tomate parfumée en grande quantité, à mettre en bocaux pour 6 mois. Le Cookeo concentre les saveurs.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 20,
    temps_cuisson: 30,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["COOKEO"],
    categories: ["accompagnement"],
    regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["sauce tomate", "conserve", "italien", "été"],
    calories_par_portion: 80,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Tomates mûres", quantite: 2000, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Oignons", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Ail", quantite: 6, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Carotte", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Basilic frais", quantite: 30, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Origan séché", quantite: 10, unite: "g", categorie: "Condiments" },
      { nom: "Sucre", quantite: 10, unite: "g", categorie: "Épicerie" },
      { nom: "Huile d'olive", quantite: 60, unite: "ml", categorie: "Condiments" },
      { nom: "Sel", quantite: 10, unite: "g", categorie: "Condiments" },
      { nom: "Poivre", quantite: 3, unite: "g", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Inciser les tomates en croix, les ébouillanter 30 sec. Peler, épépiner et concasser." },
      { numero: 2, instruction: "Mode Dorer : faire suer oignons hachés, ail et carotte râpée dans l'huile 5 min." },
      { numero: 3, instruction: "Ajouter tomates, sucre, sel, poivre, origan. Programme Mijotage 25 minutes.", duree: 1500 },
      { numero: 4, instruction: "Ajouter le basilic ciselé en fin de cuisson. Mixer si désiré." },
      { numero: 5, instruction: "Verser chaud dans des bocaux stérilisés. Fermer hermétiquement. Conservation 6 mois.", conseil: "Idéal pour pâtes, pizzas, ou base de plats mijotés." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  // ═══════════════════════════════════════════════════════════
  //                    CUISEUR RIZ (10)
  // ═══════════════════════════════════════════════════════════

  {
    slug: "riz-cantonais-cuiseur-riz",
    titre: "Riz cantonais aux crevettes",
    description: "Le riz cantonais classique avec crevettes, jambon, omelette et petits pois. Tout cuit dans le cuiseur.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 20,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_RIZ"],
    categories: ["plat"],
    regime: ["sans-lactose"],
    tags: ["riz cantonais", "chinois", "crevettes"],
    calories_par_portion: 380,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Riz long grain", quantite: 300, unite: "g", categorie: "Épicerie" },
      { nom: "Eau", quantite: 450, unite: "ml", categorie: "Autre" },
      { nom: "Crevettes décortiquées", quantite: 200, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Jambon blanc en dés", quantite: 150, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Petits pois surgelés", quantite: 150, unite: "g", categorie: "Surgelés" },
      { nom: "Œufs", quantite: 3, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Oignons verts", quantite: 4, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Sauce soja", quantite: 30, unite: "ml", categorie: "Condiments" },
      { nom: "Huile de sésame", quantite: 10, unite: "ml", categorie: "Condiments" },
      { nom: "Huile neutre", quantite: 20, unite: "ml", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Rincer le riz. Le mettre dans le cuiseur avec l'eau. Programme Riz blanc.", duree: 1200 },
      { numero: 2, instruction: "Pendant ce temps, battre les œufs. Faire une omelette plate dans une poêle, la rouler et la couper en lamelles." },
      { numero: 3, instruction: "Faire revenir crevettes et jambon dans l'huile neutre 3 min." },
      { numero: 4, instruction: "Quand le riz est cuit, mélanger avec les crevettes-jambon, l'omelette, les petits pois (préalablement décongelés), oignons verts émincés, sauce soja et huile de sésame.", conseil: "Pour un goût plus authentique, utiliser du riz refroidi de la veille." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "riz-pilaf-legumes-cuiseur-riz",
    titre: "Riz pilaf aux légumes du soleil",
    description: "Un riz pilaf coloré aux courgettes, poivrons et tomates. Plat complet végétarien parfumé aux herbes.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 25,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_RIZ"],
    categories: ["plat", "accompagnement"],
    regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["riz pilaf", "légumes", "méditerranéen", "végétarien"],
    calories_par_portion: 320,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Riz long grain", quantite: 300, unite: "g", categorie: "Épicerie" },
      { nom: "Courgette", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Poivron rouge", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Poivron jaune", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Tomates", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Oignon", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Ail", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Bouillon de légumes", quantite: 600, unite: "ml", categorie: "Épicerie" },
      { nom: "Huile d'olive", quantite: 30, unite: "ml", categorie: "Condiments" },
      { nom: "Herbes de Provence", quantite: 5, unite: "g", categorie: "Condiments" },
      { nom: "Persil plat", quantite: 10, unite: "g", categorie: "Fruits & Légumes" },
    ],
    etapes: [
      { numero: 1, instruction: "Couper tous les légumes en petits dés." },
      { numero: 2, instruction: "Mode Cuisson rapide ou Sauté : faire suer oignon et ail dans l'huile, puis ajouter les légumes 5 min." },
      { numero: 3, instruction: "Ajouter le riz, le bouillon et les herbes. Programme Riz blanc.", duree: 1500 },
      { numero: 4, instruction: "Aérer à la fourchette à la fin. Parsemer de persil." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "porridge-avoine-fruits-cuiseur-riz",
    titre: "Porridge crémeux aux fruits rouges",
    description: "Le porridge anglais crémeux aux flocons d'avoine, garni de fruits rouges et miel. Petit-déjeuner sain et énergétique.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 5,
    temps_cuisson: 15,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_RIZ"],
    categories: ["petit-dejeuner"],
    regime: ["vegetarien"],
    tags: ["porridge", "avoine", "fruits rouges", "petit-déjeuner"],
    calories_par_portion: 280,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Flocons d'avoine", quantite: 200, unite: "g", categorie: "Épicerie" },
      { nom: "Lait", quantite: 600, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Eau", quantite: 200, unite: "ml", categorie: "Autre" },
      { nom: "Miel", quantite: 40, unite: "g", categorie: "Épicerie" },
      { nom: "Cannelle", quantite: 3, unite: "g", categorie: "Condiments" },
      { nom: "Fruits rouges (frais ou surgelés)", quantite: 200, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Amandes effilées", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Pincée de sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre flocons, lait, eau, cannelle et sel dans le cuiseur." },
      { numero: 2, instruction: "Programme Bouillie ou Porridge (selon modèle), 15 min.", duree: 900 },
      { numero: 3, instruction: "Mélanger, ajouter le miel. Servir dans des bols, garnir de fruits rouges et amandes effilées." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "biriyani-poulet-cuiseur-riz",
    titre: "Biryani de poulet aux épices",
    description: "Le biryani indien parfumé aux épices, riz basmati et poulet mariné. Plat festif typique du sous-continent.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 25,
    temps_cuisson: 30,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_RIZ"],
    categories: ["plat"],
    regime: [],
    tags: ["biryani", "indien", "poulet", "épices"],
    calories_par_portion: 480,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Riz basmati", quantite: 400, unite: "g", categorie: "Épicerie" },
      { nom: "Cuisses de poulet désossées", quantite: 600, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Yaourt nature", quantite: 200, unite: "g", categorie: "Produits laitiers" },
      { nom: "Oignons", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Ail", quantite: 4, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Gingembre frais", quantite: 20, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Eau", quantite: 600, unite: "ml", categorie: "Autre" },
      { nom: "Beurre clarifié (ghee)", quantite: 40, unite: "g", categorie: "Produits laitiers" },
      { nom: "Garam masala", quantite: 10, unite: "g", categorie: "Condiments" },
      { nom: "Curcuma", quantite: 5, unite: "g", categorie: "Condiments" },
      { nom: "Cumin moulu", quantite: 5, unite: "g", categorie: "Condiments" },
      { nom: "Pistils de safran", quantite: 0.2, unite: "g", categorie: "Condiments" },
      { nom: "Lait tiède", quantite: 30, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Coriandre fraîche", quantite: 15, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Menthe fraîche", quantite: 10, unite: "g", categorie: "Fruits & Légumes" },
    ],
    etapes: [
      { numero: 1, instruction: "Mariner le poulet 15 min avec yaourt, ail et gingembre râpés, garam masala, curcuma, cumin." },
      { numero: 2, instruction: "Faire revenir oignons émincés dans le ghee jusqu'à brunissement. En réserver la moitié." },
      { numero: 3, instruction: "Ajouter le poulet mariné dans le cuiseur, faire dorer 5 min en mode Sauté." },
      { numero: 4, instruction: "Ajouter le riz rincé et l'eau. Programme Riz basmati ou Mijotage doux 25 min.", duree: 1500 },
      { numero: 5, instruction: "Faire infuser le safran dans le lait tiède, verser sur le riz à mi-cuisson." },
      { numero: 6, instruction: "Servir parsemé d'oignons frits, coriandre et menthe ciselées." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "riz-coco-cuiseur-riz",
    titre: "Riz parfumé au lait de coco",
    description: "Un riz exotique cuit au lait de coco, parfait pour accompagner curry asiatique ou plat épicé.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 5,
    temps_cuisson: 20,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_RIZ"],
    categories: ["accompagnement"],
    regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["riz coco", "thaï", "asiatique", "accompagnement"],
    calories_par_portion: 280,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Riz thaï parfumé", quantite: 300, unite: "g", categorie: "Épicerie" },
      { nom: "Lait de coco", quantite: 400, unite: "ml", categorie: "Épicerie" },
      { nom: "Eau", quantite: 200, unite: "ml", categorie: "Autre" },
      { nom: "Citronnelle", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Feuille de combava", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Sucre", quantite: 5, unite: "g", categorie: "Épicerie" },
      { nom: "Sel", quantite: 3, unite: "g", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Rincer le riz à l'eau claire jusqu'à ce qu'elle soit transparente." },
      { numero: 2, instruction: "Mettre tous les ingrédients dans le cuiseur. Écraser la citronnelle au plat du couteau." },
      { numero: 3, instruction: "Programme Riz blanc.", duree: 1200 },
      { numero: 4, instruction: "Retirer citronnelle et combava avant de servir. Aérer à la fourchette." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "riz-au-lait-cuiseur-riz",
    titre: "Riz au lait à la vanille",
    description: "Le riz au lait crémeux de notre enfance, parfumé à la vanille. Le cuiseur évite de surveiller et remuer.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 5,
    temps_cuisson: 35,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_RIZ"],
    categories: ["dessert"],
    regime: ["vegetarien", "sans-gluten"],
    tags: ["riz au lait", "vanille", "dessert", "enfance"],
    calories_par_portion: 280,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Riz rond (Arborio)", quantite: 200, unite: "g", categorie: "Épicerie" },
      { nom: "Lait entier", quantite: 1000, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Sucre", quantite: 80, unite: "g", categorie: "Épicerie" },
      { nom: "Gousse de vanille", quantite: 1, unite: "pièce", categorie: "Épicerie" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Fendre la gousse de vanille en deux et gratter les graines." },
      { numero: 2, instruction: "Mettre tous les ingrédients dans le cuiseur." },
      { numero: 3, instruction: "Programme Bouillie ou Porridge 30-35 min.", duree: 2100, conseil: "Le riz doit être tendre et la consistance crémeuse." },
      { numero: 4, instruction: "Servir tiède ou froid. Saupoudrer de cannelle ou caramel selon les goûts." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "quinoa-legumes-cuiseur-riz",
    titre: "Quinoa aux légumes croquants",
    description: "Une bowl de quinoa avec légumes du moment, parfait en plat complet végétarien ou en lunch box.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 18,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_RIZ"],
    categories: ["plat", "accompagnement"],
    regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["quinoa", "légumes", "végétarien", "healthy"],
    calories_par_portion: 280,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Quinoa", quantite: 250, unite: "g", categorie: "Épicerie" },
      { nom: "Eau", quantite: 500, unite: "ml", categorie: "Autre" },
      { nom: "Concombre", quantite: 0.5, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Tomates cerises", quantite: 200, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Avocat", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Maïs doux", quantite: 100, unite: "g", categorie: "Épicerie" },
      { nom: "Feta", quantite: 100, unite: "g", categorie: "Produits laitiers" },
      { nom: "Citron", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Huile d'olive", quantite: 30, unite: "ml", categorie: "Condiments" },
      { nom: "Menthe fraîche", quantite: 10, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Sel", quantite: 3, unite: "g", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Rincer le quinoa. Le mettre dans le cuiseur avec l'eau et le sel." },
      { numero: 2, instruction: "Programme Riz blanc 15 min.", duree: 900, conseil: "Le quinoa est cuit quand le germe blanc se détache." },
      { numero: 3, instruction: "Laisser refroidir. Mélanger avec concombre en dés, tomates cerises coupées, avocat, maïs." },
      { numero: 4, instruction: "Ajouter feta émiettée, menthe ciselée. Assaisonner d'huile d'olive et jus de citron." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "riz-jollof-cuiseur-riz",
    titre: "Jollof rice africain",
    description: "Le riz jollof, plat star de l'Afrique de l'Ouest. Riz tomaté épicé, plat de fête nigérian et ghanéen.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 30,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_RIZ"],
    categories: ["plat"],
    regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["jollof", "africain", "nigérian", "tomate"],
    calories_par_portion: 380,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Riz long grain", quantite: 400, unite: "g", categorie: "Épicerie" },
      { nom: "Tomates pelées", quantite: 400, unite: "g", categorie: "Épicerie" },
      { nom: "Poivron rouge", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Oignons", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Ail", quantite: 3, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Concentré de tomate", quantite: 50, unite: "g", categorie: "Épicerie" },
      { nom: "Bouillon de volaille", quantite: 700, unite: "ml", categorie: "Épicerie" },
      { nom: "Piment Scotch Bonnet", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Gingembre frais", quantite: 15, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Curry en poudre", quantite: 5, unite: "g", categorie: "Condiments" },
      { nom: "Thym séché", quantite: 5, unite: "g", categorie: "Condiments" },
      { nom: "Feuille de laurier", quantite: 2, unite: "pièce", categorie: "Condiments" },
      { nom: "Huile végétale", quantite: 50, unite: "ml", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mixer tomates pelées, poivron, 1 oignon, ail, gingembre et piment pour obtenir une sauce." },
      { numero: 2, instruction: "Mode Sauté : faire revenir l'oignon restant émincé dans l'huile 3 min. Ajouter concentré de tomate, faire revenir 2 min." },
      { numero: 3, instruction: "Verser la sauce mixée. Cuire 10 min en remuant pour évaporer l'eau et concentrer.", duree: 600 },
      { numero: 4, instruction: "Ajouter le riz rincé, bouillon, curry, thym, laurier. Programme Riz blanc.", duree: 1500 },
      { numero: 5, instruction: "À mi-cuisson, soulever doucement à la fourchette. Servir avec du poulet ou du poisson grillé." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "risotto-encre-seiche-cuiseur-riz",
    titre: "Risotto à l'encre de seiche",
    description: "Le risotto noir vénitien à l'encre de seiche, sophistication italienne au cuiseur à riz.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 25,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_RIZ"],
    categories: ["plat"],
    regime: ["sans-gluten"],
    tags: ["risotto", "encre de seiche", "vénitien", "italien"],
    calories_par_portion: 420,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Riz Carnaroli", quantite: 320, unite: "g", categorie: "Épicerie" },
      { nom: "Calamars", quantite: 300, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Encre de seiche", quantite: 12, unite: "g", categorie: "Condiments" },
      { nom: "Vin blanc sec", quantite: 100, unite: "ml", categorie: "Boissons" },
      { nom: "Bouillon de poisson", quantite: 1000, unite: "ml", categorie: "Épicerie" },
      { nom: "Échalotes", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Ail", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Beurre", quantite: 40, unite: "g", categorie: "Produits laitiers" },
      { nom: "Parmesan râpé", quantite: 50, unite: "g", categorie: "Produits laitiers" },
      { nom: "Persil plat", quantite: 10, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Huile d'olive", quantite: 20, unite: "ml", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Couper les calamars en anneaux. Mode Sauté : faire revenir échalotes et ail dans l'huile, ajouter calamars 3 min." },
      { numero: 2, instruction: "Ajouter le riz, nacrer 1 min. Déglacer au vin blanc." },
      { numero: 3, instruction: "Délayer l'encre de seiche dans 100ml de bouillon. Verser dans le cuiseur avec le reste du bouillon." },
      { numero: 4, instruction: "Programme Risotto ou Riz, environ 18 min.", duree: 1080 },
      { numero: 5, instruction: "Hors feu, ajouter beurre et parmesan, mélanger énergiquement. Parsemer de persil.", conseil: "Servir immédiatement, le risotto attend pas." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "riz-pudding-mangue-cuiseur-riz",
    titre: "Riz au lait coco-mangue thaï",
    description: "Le célèbre Khao Niao Mamuang thaïlandais : riz gluant à la noix de coco accompagné de mangue mûre.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 30,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_RIZ"],
    categories: ["dessert"],
    regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["riz gluant", "mangue", "thaï", "coco"],
    calories_par_portion: 320,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Riz gluant thaï", quantite: 250, unite: "g", categorie: "Épicerie" },
      { nom: "Lait de coco", quantite: 400, unite: "ml", categorie: "Épicerie" },
      { nom: "Sucre de palme", quantite: 80, unite: "g", categorie: "Épicerie" },
      { nom: "Sel", quantite: 3, unite: "g", categorie: "Condiments" },
      { nom: "Mangues mûres", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Graines de sésame grillées", quantite: 15, unite: "g", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Faire tremper le riz gluant 4 heures (idéalement la nuit).", duree: 14400, conseil: "Étape essentielle pour la texture authentique." },
      { numero: 2, instruction: "Égoutter le riz. Le mettre dans le panier vapeur du cuiseur (sur du papier sulfurisé). Programme Vapeur 25 min.", duree: 1500 },
      { numero: 3, instruction: "Pendant ce temps, chauffer 300ml de lait de coco avec sucre de palme et sel jusqu'à dissolution." },
      { numero: 4, instruction: "Verser le mélange chaud sur le riz cuit. Mélanger délicatement. Laisser reposer 10 min couvert.", duree: 600 },
      { numero: 5, instruction: "Servir avec mangue en tranches, filet du lait de coco restant et sésame grillé." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  // ═══════════════════════════════════════════════════════════
  //                    CUISEUR VAPEUR (10)
  // ═══════════════════════════════════════════════════════════

  {
    slug: "saumon-vapeur-aneth-cuiseur-vapeur",
    titre: "Saumon vapeur à l'aneth",
    description: "Un saumon vapeur fondant, parfumé à l'aneth et citron. Cuisson douce qui préserve les oméga-3.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 5,
    temps_cuisson: 12,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_VAPEUR"],
    categories: ["plat"],
    regime: ["sans-gluten", "sans-lactose"],
    tags: ["saumon", "vapeur", "aneth", "healthy"],
    calories_par_portion: 280,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Pavés de saumon", quantite: 4, unite: "pièce", categorie: "Viandes & Poissons" },
      { nom: "Citron jaune", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Aneth frais", quantite: 15, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Huile d'olive", quantite: 15, unite: "ml", categorie: "Condiments" },
      { nom: "Sel", quantite: 3, unite: "g", categorie: "Condiments" },
      { nom: "Poivre", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Saler et poivrer les pavés de saumon. Disposer dans le panier vapeur sur du papier sulfurisé." },
      { numero: 2, instruction: "Garnir de rondelles de citron et brins d'aneth." },
      { numero: 3, instruction: "Cuire à la vapeur 100°C pendant 12 min.", duree: 720, conseil: "Le saumon est cuit quand il est rosé à cœur et se détache facilement." },
      { numero: 4, instruction: "Arroser d'huile d'olive avant de servir. Accompagner de riz vapeur ou pommes de terre nouvelles." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "couscous-vapeur-cuiseur-vapeur",
    titre: "Semoule de couscous vapeur traditionnelle",
    description: "La semoule traditionnelle marocaine roulée et cuite à la vapeur en 3 fois. Texture aérienne et grains détachés.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 20,
    temps_cuisson: 45,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_VAPEUR"],
    categories: ["accompagnement"],
    regime: ["vegan", "sans-lactose"],
    tags: ["couscous", "marocain", "semoule", "tradition"],
    calories_par_portion: 320,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Semoule moyenne", quantite: 500, unite: "g", categorie: "Épicerie" },
      { nom: "Eau tiède salée", quantite: 250, unite: "ml", categorie: "Autre" },
      { nom: "Huile d'olive", quantite: 50, unite: "ml", categorie: "Condiments" },
      { nom: "Beurre", quantite: 50, unite: "g", categorie: "Produits laitiers" },
      { nom: "Sel", quantite: 5, unite: "g", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Verser la semoule dans un grand plat. Arroser d'1 c. à s. d'huile, mélanger pour enrober chaque grain." },
      { numero: 2, instruction: "Verser 100ml d'eau tiède salée, mélanger à la main pour humidifier uniformément. Laisser gonfler 10 min.", duree: 600 },
      { numero: 3, instruction: "Mettre dans le panier vapeur. Cuire 15 min à la vapeur.", duree: 900 },
      { numero: 4, instruction: "Reverser dans le plat. Aérer à la fourchette. Ajouter eau (50ml), huile, sel. Remettre 10 min vapeur.", duree: 600 },
      { numero: 5, instruction: "Répéter une 3e fois pour 10 min vapeur. Ajouter le beurre en parcelles, mélanger.", duree: 600, conseil: "Cette triple cuisson est le secret d'une semoule légère et non agglomérée." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "ravioles-chinois-vapeur-cuiseur-vapeur",
    titre: "Ravioles chinois jiaozi",
    description: "Les fameux raviolis chinois farcis au porc et chou. Version vapeur, plus saine que la version frite.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 45,
    temps_cuisson: 12,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_VAPEUR"],
    categories: ["plat", "aperitif"],
    regime: ["sans-lactose"],
    tags: ["ravioles", "jiaozi", "chinois", "porc"],
    calories_par_portion: 360,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Pâte à raviolis chinois (gyoza)", quantite: 32, unite: "pièce", categorie: "Épicerie" },
      { nom: "Porc haché", quantite: 400, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Chou chinois", quantite: 200, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Oignons verts", quantite: 4, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Gingembre frais râpé", quantite: 15, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Sauce soja", quantite: 30, unite: "ml", categorie: "Condiments" },
      { nom: "Huile de sésame", quantite: 10, unite: "ml", categorie: "Condiments" },
      { nom: "Vin de Shaoxing (ou Xérès)", quantite: 15, unite: "ml", categorie: "Boissons" },
      { nom: "Sucre", quantite: 3, unite: "g", categorie: "Épicerie" },
      { nom: "Sel", quantite: 3, unite: "g", categorie: "Condiments" },
      { nom: "Vinaigre de riz", quantite: 30, unite: "ml", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Émincer finement le chou, le saler et laisser dégorger 10 min. Presser pour extraire l'eau." },
      { numero: 2, instruction: "Mélanger porc, chou, oignons verts émincés, gingembre, sauce soja, sésame, vin, sucre." },
      { numero: 3, instruction: "Garnir chaque pâte d'1 c. à c. de farce. Humidifier les bords, replier en demi-lune et plisser." },
      { numero: 4, instruction: "Disposer dans le panier vapeur sur du papier sulfurisé sans se toucher." },
      { numero: 5, instruction: "Cuire à la vapeur 12 min.", duree: 720, conseil: "Servir avec sauce trempette : sauce soja + vinaigre de riz + huile de sésame." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "legumes-vapeur-aioli-cuiseur-vapeur",
    titre: "Légumes vapeur sauce aïoli",
    description: "Une sélection de légumes de saison cuits vapeur, servis avec un aïoli maison à l'ail et huile d'olive.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 18,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_VAPEUR"],
    categories: ["accompagnement", "entree"],
    regime: ["vegetarien", "sans-gluten"],
    tags: ["légumes vapeur", "aïoli", "provençal", "healthy"],
    calories_par_portion: 280,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Pommes de terre nouvelles", quantite: 400, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Carottes", quantite: 4, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Brocoli", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Haricots verts", quantite: 250, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Œufs", quantite: 4, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Jaune d'œuf (aïoli)", quantite: 1, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Ail", quantite: 4, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Huile d'olive", quantite: 200, unite: "ml", categorie: "Condiments" },
      { nom: "Citron", quantite: 0.5, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Sel", quantite: 5, unite: "g", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Disposer pommes de terre et carottes en bâtonnets dans le panier. Cuire à la vapeur 12 min.", duree: 720 },
      { numero: 2, instruction: "Ajouter brocoli en bouquets, haricots verts et œufs. Continuer 8 min.", duree: 480 },
      { numero: 3, instruction: "Préparer l'aïoli : écraser l'ail au pilon avec le sel. Ajouter le jaune d'œuf, monter avec l'huile en filet comme une mayo." },
      { numero: 4, instruction: "Ajouter le jus de citron à l'aïoli. Servir avec les légumes et les œufs durs écalés." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "panna-cotta-vapeur-cuiseur-vapeur",
    titre: "Panna cotta vanille à la vapeur",
    description: "La panna cotta italienne crémeuse, sans risque de débordement grâce à la cuisson vapeur douce.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 25,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_VAPEUR"],
    categories: ["dessert"],
    regime: ["vegetarien", "sans-gluten"],
    tags: ["panna cotta", "italien", "vanille", "vapeur"],
    calories_par_portion: 280,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Crème liquide entière", quantite: 500, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Lait", quantite: 200, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Sucre", quantite: 80, unite: "g", categorie: "Épicerie" },
      { nom: "Gousse de vanille", quantite: 1, unite: "pièce", categorie: "Épicerie" },
      { nom: "Œufs", quantite: 3, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Coulis de fruits rouges", quantite: 100, unite: "g", categorie: "Fruits & Légumes" },
    ],
    etapes: [
      { numero: 1, instruction: "Chauffer crème, lait et sucre avec la gousse de vanille fendue jusqu'à frémissement. Laisser infuser 10 min hors feu." },
      { numero: 2, instruction: "Battre légèrement les œufs. Verser la crème chaude (filtrée) sur les œufs en remuant." },
      { numero: 3, instruction: "Verser dans 6 ramequins. Couvrir de film alimentaire (ou aluminium)." },
      { numero: 4, instruction: "Cuire au panier vapeur 25 min.", duree: 1500, conseil: "La panna cotta doit trembler légèrement au centre, elle se solidifie en refroidissant." },
      { numero: 5, instruction: "Refroidir 4h au frigo. Servir avec coulis de fruits rouges.", duree: 14400 },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "papillote-cabillaud-vapeur-cuiseur-vapeur",
    titre: "Papillotes de cabillaud aux légumes",
    description: "Cabillaud cuit en papillote vapeur sur lit de courgettes et tomates. Cuisson saine qui concentre les saveurs.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 15,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_VAPEUR"],
    categories: ["plat"],
    regime: ["sans-gluten", "sans-lactose"],
    tags: ["cabillaud", "papillote", "vapeur", "healthy"],
    calories_par_portion: 220,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Filets de cabillaud", quantite: 4, unite: "pièce", categorie: "Viandes & Poissons" },
      { nom: "Courgettes", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Tomates", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Échalotes", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Citron", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Thym frais", quantite: 5, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Huile d'olive", quantite: 30, unite: "ml", categorie: "Condiments" },
      { nom: "Sel", quantite: 3, unite: "g", categorie: "Condiments" },
      { nom: "Poivre", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Découper 4 grandes feuilles de papier sulfurisé. Disposer sur chacune des rondelles fines de courgette et tomate." },
      { numero: 2, instruction: "Poser un filet de cabillaud dessus. Saler, poivrer. Garnir d'échalote ciselée, thym, rondelle de citron et filet d'huile." },
      { numero: 3, instruction: "Fermer les papillotes hermétiquement. Disposer dans le panier vapeur." },
      { numero: 4, instruction: "Cuire à la vapeur 15 min.", duree: 900, conseil: "Servir directement dans la papillote pour le théâtre des arômes." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "asperges-vapeur-hollandaise-cuiseur-vapeur",
    titre: "Asperges vertes sauce hollandaise",
    description: "Des asperges vertes croquantes vapeur, accompagnées d'une sauce hollandaise montée au beurre. Plat printanier.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 10,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_VAPEUR"],
    categories: ["entree", "accompagnement"],
    regime: ["vegetarien", "sans-gluten"],
    tags: ["asperges", "hollandaise", "printemps", "élégant"],
    calories_par_portion: 280,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Asperges vertes", quantite: 800, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Jaunes d'œufs", quantite: 4, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Beurre clarifié", quantite: 250, unite: "g", categorie: "Produits laitiers" },
      { nom: "Citron", quantite: 0.5, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Sel", quantite: 3, unite: "g", categorie: "Condiments" },
      { nom: "Poivre blanc", quantite: 1, unite: "pincée", categorie: "Condiments" },
      { nom: "Eau", quantite: 30, unite: "ml", categorie: "Autre" },
    ],
    etapes: [
      { numero: 1, instruction: "Casser le bout dur des asperges. Disposer dans le panier vapeur." },
      { numero: 2, instruction: "Cuire vapeur 8-10 min selon l'épaisseur.", duree: 600, conseil: "Vérifier la cuisson avec la pointe d'un couteau, elles doivent rester un peu fermes." },
      { numero: 3, instruction: "Préparer la hollandaise : fouetter jaunes et eau au bain-marie jusqu'à émulsion mousseuse." },
      { numero: 4, instruction: "Hors feu, incorporer le beurre clarifié tiède en filet en fouettant. Saler, poivrer, jus de citron." },
      { numero: 5, instruction: "Servir les asperges nappées de sauce hollandaise tiède." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "boudoirs-vapeur-vanille-cuiseur-vapeur",
    titre: "Petits gâteaux vapeur à la vanille",
    description: "Des gâteaux moelleux et aériens cuits vapeur, version chinoise façon Ma Lai Go. Texture unique en bouche.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 25,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_VAPEUR"],
    categories: ["dessert", "petit-dejeuner"],
    regime: ["vegetarien"],
    tags: ["gâteau vapeur", "Ma Lai Go", "chinois", "moelleux"],
    calories_par_portion: 240,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Farine", quantite: 200, unite: "g", categorie: "Épicerie" },
      { nom: "Sucre roux", quantite: 100, unite: "g", categorie: "Épicerie" },
      { nom: "Œufs", quantite: 3, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Lait", quantite: 100, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Huile végétale", quantite: 60, unite: "ml", categorie: "Condiments" },
      { nom: "Levure chimique", quantite: 8, unite: "g", categorie: "Épicerie" },
      { nom: "Vanille", quantite: 5, unite: "ml", categorie: "Épicerie" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Battre œufs et sucre 5 min jusqu'à blanchiment et triplement de volume." },
      { numero: 2, instruction: "Ajouter délicatement lait, huile, vanille. Incorporer farine et levure tamisées." },
      { numero: 3, instruction: "Verser dans des moules à muffins en silicone aux 2/3. Disposer dans le panier vapeur." },
      { numero: 4, instruction: "Cuire vapeur 25 min sans ouvrir.", duree: 1500, conseil: "La cuisson vapeur donne une texture aérienne unique. Ne jamais ouvrir pendant la cuisson." },
      { numero: 5, instruction: "Démouler tiède. Saupoudrer de sucre glace si désiré." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "filet-mignon-porc-vapeur-cuiseur-vapeur",
    titre: "Filet mignon de porc vapeur miel-soja",
    description: "Un filet mignon mariné miel-soja, cuit vapeur. Tendre et savoureux, version healthy de la cuisson au four.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 30,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_VAPEUR"],
    categories: ["plat"],
    regime: ["sans-gluten", "sans-lactose"],
    tags: ["filet mignon", "porc", "miel-soja", "asiatique"],
    calories_par_portion: 320,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Filet mignon de porc", quantite: 700, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Sauce soja", quantite: 60, unite: "ml", categorie: "Condiments" },
      { nom: "Miel", quantite: 40, unite: "g", categorie: "Épicerie" },
      { nom: "Gingembre frais", quantite: 15, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Ail", quantite: 3, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Cinq-épices", quantite: 5, unite: "g", categorie: "Condiments" },
      { nom: "Huile de sésame", quantite: 10, unite: "ml", categorie: "Condiments" },
      { nom: "Graines de sésame", quantite: 10, unite: "g", categorie: "Épicerie" },
      { nom: "Oignons verts", quantite: 3, unite: "pièce", categorie: "Fruits & Légumes" },
    ],
    etapes: [
      { numero: 1, instruction: "Mélanger sauce soja, miel, gingembre et ail râpés, cinq-épices et huile de sésame." },
      { numero: 2, instruction: "Mariner le filet mignon 1 heure dans cette préparation.", duree: 3600 },
      { numero: 3, instruction: "Disposer le filet sur du papier sulfurisé dans le panier vapeur. Réserver la marinade." },
      { numero: 4, instruction: "Cuire à la vapeur 30 min, en badigeonnant de marinade à mi-cuisson.", duree: 1800 },
      { numero: 5, instruction: "Trancher en biais. Parsemer de graines de sésame et oignons verts émincés. Servir avec riz vapeur." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "artichauts-vapeur-vinaigrette-cuiseur-vapeur",
    titre: "Artichauts vapeur sauce ravigote",
    description: "Des artichauts entiers cuits vapeur, accompagnés d'une sauce ravigote aux câpres et fines herbes. Entrée traditionnelle.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 35,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_VAPEUR"],
    categories: ["entree", "aperitif"],
    regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["artichauts", "vinaigrette", "français", "tradition"],
    calories_par_portion: 180,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Artichauts moyens", quantite: 4, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Citron", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Huile d'olive", quantite: 60, unite: "ml", categorie: "Condiments" },
      { nom: "Vinaigre de vin blanc", quantite: 20, unite: "ml", categorie: "Condiments" },
      { nom: "Moutarde", quantite: 10, unite: "g", categorie: "Condiments" },
      { nom: "Câpres", quantite: 30, unite: "g", categorie: "Condiments" },
      { nom: "Cornichons", quantite: 3, unite: "pièce", categorie: "Condiments" },
      { nom: "Échalote", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Persil plat", quantite: 10, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Cerfeuil", quantite: 5, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Estragon", quantite: 3, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Sel", quantite: 3, unite: "g", categorie: "Condiments" },
      { nom: "Poivre", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Couper la queue des artichauts au ras et les pointes des feuilles. Frotter de citron pour éviter le noircissement." },
      { numero: 2, instruction: "Disposer dans le panier vapeur, fond vers le bas. Cuire 35 min à la vapeur.", duree: 2100, conseil: "Les artichauts sont cuits quand une feuille se détache facilement." },
      { numero: 3, instruction: "Préparer la sauce ravigote : mélanger moutarde, vinaigre, sel, poivre. Émulsionner avec l'huile en filet." },
      { numero: 4, instruction: "Ajouter câpres, cornichons hachés, échalote ciselée, fines herbes hachées." },
      { numero: 5, instruction: "Servir les artichauts tièdes avec la sauce à part.", conseil: "Manger en effeuillant et trempant la base de chaque feuille dans la sauce." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },
];
