/* =============================================================
   Kitchen Mix — Seed Extra 2026 (35 recettes nouvelles)
   -------------------------------------------------------------
   Lot complémentaire pour enrichir la base — toutes les recettes
   sont vérifiées pour ne pas dupliquer les slugs existants.

   Répartition :
     • Thermomix (TM5/TM6/TM7) : 5
     • Magimix Cook Expert      : 5
     • Moulinex Companion       : 5
     • Petits appareils         : 20

   Pour activer : ajouter dans scripts/seed-mega.ts :
     import { SEED_EXTRA_2026 } from "../lib/seed-extra-2026";
     ...puis dans ALL_RECIPES, ajouter ...SEED_EXTRA_2026
   ============================================================= */

import type { SeedRecette } from "./seed-data";

export const SEED_EXTRA_2026: SeedRecette[] = [

  // ═══════════════════════════════════════════════════════════
  //                       THERMOMIX (5)
  // ═══════════════════════════════════════════════════════════

  {
    slug: "tagliatelles-fraiches-thermomix",
    titre: "Tagliatelles fraîches maison",
    description: "Des pâtes fraîches aux œufs, pétries au Thermomix puis étalées et coupées. Le secret d'un repas italien authentique.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 25,
    temps_cuisson: 3,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["TM5", "TM6", "TM7"],
    categories: ["plat", "boulangerie"],
    regime: ["vegetarien"],
    tags: ["pâtes fraîches", "italien", "tagliatelles", "maison"],
    calories_par_portion: 380,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Farine T55", quantite: 400, unite: "g", categorie: "Épicerie" },
      { nom: "Œufs entiers", quantite: 4, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Huile d'olive", quantite: 10, unite: "ml", categorie: "Condiments" },
      { nom: "Sel fin", quantite: 5, unite: "g", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre la farine, les œufs, l'huile et le sel dans le bol.", vitesse: 4, duree: 30 },
      { numero: 2, instruction: "Pétrir au mode Pétrin (Épi).", duree: 180, conseil: "La pâte doit être lisse et non collante. Ajouter 1 c. à s. de farine si besoin." },
      { numero: 3, instruction: "Filmer la pâte et laisser reposer 30 min au frais." },
      { numero: 4, instruction: "Diviser en 4 boules. Étaler chaque boule très finement au laminoir (cran 6/7). Couper en tagliatelles." },
      { numero: 5, instruction: "Plonger dans l'eau bouillante salée 2-3 minutes selon l'épaisseur.", duree: 180, conseil: "Les pâtes fraîches cuisent très vite, surveiller dès qu'elles remontent." },
    ],
    faq: [
      { question: "Combien de temps se conservent les tagliatelles fraîches ?", reponse: "Crues : 2 jours au frigo enroulées en nids, ou 2 mois au congélateur. Cuites : à manger dans la journée." },
    ],
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "cookies-pepites-chocolat-thermomix",
    titre: "Cookies américains aux pépites",
    description: "Les vrais cookies américains : croustillants en bord, fondants au cœur, dégoulinants de pépites de chocolat.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 12,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["TM5", "TM6", "TM7"],
    categories: ["dessert", "petit-dejeuner"],
    regime: ["vegetarien"],
    tags: ["cookies", "chocolat", "américain", "goûter"],
    calories_par_portion: 320,
    nutriscore: "D",
    nutriscore_note: "Riche en sucre et lipides",
    ingredients: [
      { nom: "Beurre mou", quantite: 150, unite: "g", categorie: "Produits laitiers" },
      { nom: "Sucre roux (cassonade)", quantite: 120, unite: "g", categorie: "Épicerie" },
      { nom: "Sucre blanc", quantite: 50, unite: "g", categorie: "Épicerie" },
      { nom: "Œuf entier", quantite: 1, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Extrait de vanille", quantite: 5, unite: "ml", categorie: "Épicerie" },
      { nom: "Farine T45", quantite: 280, unite: "g", categorie: "Épicerie" },
      { nom: "Levure chimique", quantite: 5, unite: "g", categorie: "Épicerie" },
      { nom: "Sel", quantite: 2, unite: "g", categorie: "Condiments" },
      { nom: "Pépites de chocolat noir", quantite: 200, unite: "g", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre le beurre mou et les deux sucres dans le bol. Crémer.", vitesse: 4, duree: 60 },
      { numero: 2, instruction: "Ajouter l'œuf et la vanille.", vitesse: 4, duree: 30 },
      { numero: 3, instruction: "Ajouter farine, levure et sel.", vitesse: 3, duree: 45 },
      { numero: 4, instruction: "Incorporer les pépites en sens inverse pour ne pas les casser.", vitesse: 2, duree: 20 },
      { numero: 5, instruction: "Former 12 boules. Réfrigérer 30 min. Cuire 11-12 min à 180°C.", conseil: "Sortir du four quand le centre est encore mou — ils durciront en refroidissant." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "soupe-tomate-basilic-thermomix",
    titre: "Soupe de tomates rôties au basilic",
    description: "Une soupe de tomates onctueuse et parfumée, version méditerranéenne. Les tomates rôties apportent une profondeur unique.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 30,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["TM5", "TM6", "TM7"],
    categories: ["soupe", "entree"],
    regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["tomates", "basilic", "soupe", "méditerranéen"],
    calories_par_portion: 110,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Tomates mûres", quantite: 1000, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Oignon", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Ail", quantite: 3, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Bouillon de légumes", quantite: 400, unite: "ml", categorie: "Épicerie" },
      { nom: "Basilic frais", quantite: 15, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Huile d'olive", quantite: 30, unite: "ml", categorie: "Condiments" },
      { nom: "Sucre", quantite: 5, unite: "g", categorie: "Épicerie" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
      { nom: "Poivre", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Couper les tomates en 4 et l'oignon en quartiers. Disposer sur une plaque avec l'ail entier en chemise. Arroser d'huile d'olive et enfourner 25 min à 200°C.", duree: 1500 },
      { numero: 2, instruction: "Verser les légumes rôtis (ail épluché) dans le bol avec le bouillon, sucre, sel et poivre.", vitesse: 4, duree: 30 },
      { numero: 3, instruction: "Mixer.", vitesse: 9, duree: 60, conseil: "Pour une soupe plus lisse, mixer 30 secondes de plus." },
      { numero: 4, instruction: "Ajouter le basilic et donner 2 impulsions.", vitesse: 5, duree: 5, conseil: "Servir avec un filet d'huile d'olive et des croûtons." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "blinis-maison-thermomix",
    titre: "Blinis maison moelleux",
    description: "Des blinis russes aériens, parfaits pour l'apéro avec saumon fumé et crème. Pâte levée au sarrasin.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 10,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["TM5", "TM6", "TM7"],
    categories: ["aperitif", "entree", "boulangerie"],
    regime: ["vegetarien"],
    tags: ["blinis", "apéro", "russe", "saumon"],
    calories_par_portion: 240,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Farine de blé", quantite: 150, unite: "g", categorie: "Épicerie" },
      { nom: "Farine de sarrasin", quantite: 50, unite: "g", categorie: "Épicerie" },
      { nom: "Lait tiède", quantite: 250, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Œufs (séparés)", quantite: 2, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Levure boulangère sèche", quantite: 5, unite: "g", categorie: "Épicerie" },
      { nom: "Sel", quantite: 3, unite: "g", categorie: "Condiments" },
      { nom: "Beurre fondu", quantite: 20, unite: "g", categorie: "Produits laitiers" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre le lait dans le bol. Tiédir.", vitesse: 1, temperature: 37, duree: 90 },
      { numero: 2, instruction: "Ajouter levure, farines, sel, jaunes d'œufs et beurre fondu.", vitesse: 4, duree: 30 },
      { numero: 3, instruction: "Verser dans un saladier. Couvrir et laisser lever 1h à température ambiante.", duree: 3600 },
      { numero: 4, instruction: "Monter les blancs en neige avec le fouet papillon.", vitesse: 4, duree: 180, accessoire: "Fouet papillon" },
      { numero: 5, instruction: "Incorporer délicatement les blancs à la pâte. Cuire des petites louches dans une poêle beurrée 1 min par face.", conseil: "Servir tièdes avec saumon fumé, crème fraîche et aneth." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "fondant-citron-meringue-thermomix",
    titre: "Fondant au citron meringué",
    description: "Un gâteau fondant au citron surmonté d'une meringue dorée. L'équilibre parfait entre acidité et douceur.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 20,
    temps_cuisson: 35,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["TM5", "TM6", "TM7"],
    categories: ["dessert"],
    regime: ["vegetarien"],
    tags: ["citron", "fondant", "meringue", "dessert"],
    calories_par_portion: 340,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Citrons jaunes (zeste + jus)", quantite: 3, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Sucre", quantite: 200, unite: "g", categorie: "Épicerie" },
      { nom: "Œufs (jaunes pour le gâteau)", quantite: 4, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Beurre mou", quantite: 100, unite: "g", categorie: "Produits laitiers" },
      { nom: "Farine T45", quantite: 150, unite: "g", categorie: "Épicerie" },
      { nom: "Levure chimique", quantite: 5, unite: "g", categorie: "Épicerie" },
      { nom: "Blancs d'œufs (meringue)", quantite: 4, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Sucre (meringue)", quantite: 100, unite: "g", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Râper les zestes de citron dans le bol avec 200g de sucre.", vitesse: 9, duree: 10 },
      { numero: 2, instruction: "Ajouter beurre mou, jaunes d'œufs, farine, levure et le jus des citrons.", vitesse: 4, duree: 30 },
      { numero: 3, instruction: "Verser dans un moule beurré. Enfourner 25 min à 170°C.", duree: 1500 },
      { numero: 4, instruction: "Pendant ce temps, nettoyer le bol. Mettre les blancs et 100g de sucre. Monter en meringue ferme avec le papillon.", vitesse: 4, duree: 240, accessoire: "Fouet papillon" },
      { numero: 5, instruction: "Étaler la meringue sur le gâteau tiède. Passer au four chaleur tournante 5-8 min à 200°C jusqu'à ce qu'elle soit dorée.", conseil: "Surveiller : la meringue dore très vite." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  // ═══════════════════════════════════════════════════════════
  //                    MAGIMIX COOK EXPERT (5)
  // ═══════════════════════════════════════════════════════════

  {
    slug: "soupe-asperges-cookexpert",
    titre: "Velouté d'asperges blanches",
    description: "Un velouté printanier ultra crémeux aux asperges blanches. Le programme Soupe veloutée cuit et mixe en une étape.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 25,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["COOK_EXPERT"],
    categories: ["soupe", "entree"],
    regime: ["vegetarien", "sans-gluten"],
    tags: ["asperges", "printemps", "velouté"],
    calories_par_portion: 140,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Asperges blanches", quantite: 700, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Pomme de terre", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Échalote", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Bouillon de volaille", quantite: 800, unite: "ml", categorie: "Épicerie" },
      { nom: "Crème liquide", quantite: 100, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Beurre", quantite: 30, unite: "g", categorie: "Produits laitiers" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
      { nom: "Poivre blanc", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Éplucher les asperges en gardant les pointes pour la déco. Couper en tronçons. Émincer les échalotes.", conseil: "Garder l'eau de cuisson des épluchures pour le bouillon." },
      { numero: 2, instruction: "Faire fondre le beurre dans le bol Inox.", vitesse: 1, temperature: 100, duree: 60 },
      { numero: 3, instruction: "Ajouter les échalotes et faire suer.", vitesse: 1, temperature: 100, duree: 180 },
      { numero: 4, instruction: "Ajouter asperges, pomme de terre en cubes et bouillon. Programme Soupe veloutée.", duree: 1500 },
      { numero: 5, instruction: "Ajouter la crème, sel et poivre. Mixer 1 minute.", vitesse: 13, duree: 60, conseil: "Servir avec les pointes d'asperges blanchies en garniture." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "tarte-tatin-pommes-cookexpert",
    titre: "Tarte Tatin aux pommes caramélisées",
    description: "La tarte Tatin renversée, un classique français. Caramélisation parfaite grâce au mode rissolage du Cook Expert.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 25,
    temps_cuisson: 40,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["COOK_EXPERT"],
    categories: ["dessert"],
    regime: ["vegetarien"],
    tags: ["tarte tatin", "pomme", "caramel", "français"],
    calories_par_portion: 380,
    nutriscore: "D",
    nutriscore_note: "Riche en sucre et lipides",
    ingredients: [
      { nom: "Pommes (Reinette ou Boskoop)", quantite: 8, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Sucre", quantite: 150, unite: "g", categorie: "Épicerie" },
      { nom: "Beurre", quantite: 80, unite: "g", categorie: "Produits laitiers" },
      { nom: "Pâte feuilletée", quantite: 1, unite: "pièce", categorie: "Épicerie" },
      { nom: "Vanille en poudre", quantite: 1, unite: "pincée", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Éplucher les pommes, les couper en quartiers et les épépiner." },
      { numero: 2, instruction: "Mettre le sucre et le beurre dans le bol Inox. Lancer le programme Rissolage 5 minutes.", duree: 300, conseil: "Le caramel doit être ambré, pas brun." },
      { numero: 3, instruction: "Ajouter les pommes et la vanille. Cuire 10 minutes en mode mijoter.", temperature: 130, duree: 600 },
      { numero: 4, instruction: "Verser pommes et caramel dans un moule à tarte beurré. Recouvrir de la pâte feuilletée et rentrer les bords." },
      { numero: 5, instruction: "Enfourner 25 minutes à 200°C. Laisser tiédir 10 min puis démouler en retournant sur un plat.", duree: 1500, conseil: "Servir tiède avec une boule de glace vanille." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "mousseline-pommes-de-terre-cookexpert",
    titre: "Mousseline de pommes de terre Robuchon",
    description: "La purée la plus crémeuse au monde, à la Joël Robuchon. Beaucoup de beurre, beaucoup d'amour.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 25,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["COOK_EXPERT"],
    categories: ["accompagnement"],
    regime: ["vegetarien", "sans-gluten"],
    tags: ["purée", "mousseline", "Robuchon", "classique"],
    calories_par_portion: 380,
    nutriscore: "C",
    nutriscore_note: "Riche en lipides",
    ingredients: [
      { nom: "Pommes de terre Bintje", quantite: 1000, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Beurre froid en cubes", quantite: 250, unite: "g", categorie: "Produits laitiers" },
      { nom: "Lait entier", quantite: 250, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Sel", quantite: 5, unite: "g", categorie: "Condiments" },
      { nom: "Muscade", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Cuire les pommes de terre en robe des champs dans une casserole d'eau salée 25 minutes (départ eau froide)." },
      { numero: 2, instruction: "Pendant ce temps, mettre le lait dans le bol Inox du Cook Expert. Chauffer doucement.", vitesse: 1, temperature: 80, duree: 300 },
      { numero: 3, instruction: "Éplucher les pommes de terre encore chaudes. Les passer au moulin à légumes (grille fine) directement dans le bol." },
      { numero: 4, instruction: "Mélanger avec le mode Pâte/Gâteau. Incorporer le beurre froid en cubes petit à petit.", vitesse: 4, temperature: 80, duree: 240, conseil: "Le beurre froid émulsionne mieux. Battre énergiquement." },
      { numero: 5, instruction: "Saler, poivrer, muscade. Servir immédiatement.", conseil: "Pour encore plus crémeux, passer la mousseline au tamis fin avant de servir." },
    ],
    faq: [
      { question: "Pourquoi cuire les pommes de terre en robe des champs ?", reponse: "L'amidon est mieux préservé, et la chair ne s'imbibe pas d'eau de cuisson." },
    ],
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "clafoutis-cerises-cookexpert",
    titre: "Clafoutis aux cerises noires",
    description: "Le clafoutis traditionnel limousin aux cerises avec leurs noyaux pour plus de saveur. Préparation 5 minutes.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 35,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["COOK_EXPERT"],
    categories: ["dessert"],
    regime: ["vegetarien"],
    tags: ["clafoutis", "cerise", "limousin", "été"],
    calories_par_portion: 240,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Cerises noires", quantite: 500, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Œufs", quantite: 3, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Lait entier", quantite: 250, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Crème liquide", quantite: 100, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Farine", quantite: 80, unite: "g", categorie: "Épicerie" },
      { nom: "Sucre", quantite: 80, unite: "g", categorie: "Épicerie" },
      { nom: "Beurre (moule)", quantite: 15, unite: "g", categorie: "Produits laitiers" },
      { nom: "Vanille", quantite: 1, unite: "pincée", categorie: "Épicerie" },
      { nom: "Sucre glace", quantite: 10, unite: "g", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Beurrer un plat à clafoutis. Y disposer les cerises (avec noyaux pour la tradition)." },
      { numero: 2, instruction: "Mettre œufs, lait, crème, farine, sucre et vanille dans le bol.", vitesse: 8, duree: 30 },
      { numero: 3, instruction: "Verser la pâte sur les cerises." },
      { numero: 4, instruction: "Enfourner 35 minutes à 180°C. Le clafoutis doit être doré et juste tremblotant au centre.", duree: 2100 },
      { numero: 5, instruction: "Laisser tiédir 15 min. Saupoudrer de sucre glace.", conseil: "Le clafoutis se mange tiède ou froid, jamais brûlant." },
    ],
    faq: [
      { question: "Pourquoi garder les noyaux ?", reponse: "Ils libèrent un parfum d'amande typique. Tradition limousine. Prévenir les convives !" },
    ],
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "madeleines-coquilles-cookexpert",
    titre: "Madeleines coquilles à la bosse",
    description: "Les vraies madeleines avec leur bosse caractéristique. Le secret : un repos au frais et un choc thermique.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 12,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["COOK_EXPERT"],
    categories: ["dessert", "petit-dejeuner"],
    regime: ["vegetarien"],
    tags: ["madeleine", "Commercy", "goûter", "français"],
    calories_par_portion: 220,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Œufs", quantite: 2, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Sucre", quantite: 100, unite: "g", categorie: "Épicerie" },
      { nom: "Miel", quantite: 20, unite: "g", categorie: "Épicerie" },
      { nom: "Farine T45", quantite: 130, unite: "g", categorie: "Épicerie" },
      { nom: "Levure chimique", quantite: 5, unite: "g", categorie: "Épicerie" },
      { nom: "Beurre fondu", quantite: 120, unite: "g", categorie: "Produits laitiers" },
      { nom: "Zeste de citron", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Faire fondre le beurre dans le bol Inox.", vitesse: 1, temperature: 70, duree: 120 },
      { numero: 2, instruction: "Ajouter œufs, sucre, miel, sel et zeste. Fouetter.", vitesse: 6, duree: 60 },
      { numero: 3, instruction: "Ajouter farine et levure.", vitesse: 4, duree: 30 },
      { numero: 4, instruction: "Réfrigérer la pâte au moins 1 heure (idéalement 4h ou la nuit).", duree: 3600, conseil: "Le repos au froid est INDISPENSABLE pour la bosse." },
      { numero: 5, instruction: "Préchauffer le four à 220°C. Beurrer un moule à madeleines. Remplir aux 2/3. Enfourner 4 min à 220°C, puis baisser à 180°C et cuire 6-8 min.", duree: 720, conseil: "Le choc thermique 220→180°C crée la bosse." },
    ],
    faq: [
      { question: "Pourquoi mes madeleines n'ont pas de bosse ?", reponse: "Trois raisons : pâte pas assez froide (repos < 1h), four pas assez chaud au départ, ou trop de pâte dans les moules." },
    ],
    approuve: true,
    publie: true,
    vues: 0,
  },

  // ═══════════════════════════════════════════════════════════
  //                    MOULINEX COMPANION (5)
  // ═══════════════════════════════════════════════════════════

  {
    slug: "parmentier-canard-companion",
    titre: "Parmentier de canard confit",
    description: "Un parmentier généreux au confit de canard effiloché et purée maison. Plat du Sud-Ouest réconfortant.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 20,
    temps_cuisson: 35,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["COMPANION"],
    categories: ["plat"],
    regime: ["sans-gluten"],
    tags: ["parmentier", "canard", "confit", "sud-ouest"],
    calories_par_portion: 580,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Cuisses de canard confites", quantite: 2, unite: "pièce", categorie: "Viandes & Poissons" },
      { nom: "Pommes de terre", quantite: 800, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Lait", quantite: 200, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Beurre", quantite: 50, unite: "g", categorie: "Produits laitiers" },
      { nom: "Échalotes", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Ail", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Persil plat", quantite: 10, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Gruyère râpé", quantite: 50, unite: "g", categorie: "Produits laitiers" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
      { nom: "Poivre", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Hacher échalotes et ail dans le bol.", vitesse: 11, duree: 10 },
      { numero: 2, instruction: "Faire suer avec un peu de graisse de canard.", vitesse: 1, temperature: 130, duree: 180 },
      { numero: 3, instruction: "Ajouter le canard effiloché et le persil ciselé. Mélanger.", vitesse: 1, temperature: 100, duree: 120, conseil: "Réserver dans un plat à gratin." },
      { numero: 4, instruction: "Cuire les pommes de terre dans le panier vapeur, dans 500ml d'eau.", vitesse: 1, temperature: 120, duree: 1500, accessoire: "Panier vapeur" },
      { numero: 5, instruction: "Vider l'eau du bol. Mettre les pommes de terre cuites avec le lait, le beurre, sel et poivre. Mode purée.", vitesse: 4, duree: 30 },
      { numero: 6, instruction: "Étaler la purée sur le canard. Saupoudrer de gruyère. Enfourner 20 min à 200°C.", duree: 1200 },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "cake-olives-jambon-companion",
    titre: "Cake olives et jambon",
    description: "Le cake apéritif salé classique. Parfait pour un buffet ou un pique-nique. Moelleux à souhait.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 45,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["COMPANION"],
    categories: ["aperitif", "entree"],
    regime: [],
    tags: ["cake salé", "olives", "jambon", "apéro"],
    calories_par_portion: 320,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Farine", quantite: 200, unite: "g", categorie: "Épicerie" },
      { nom: "Œufs", quantite: 3, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Lait", quantite: 100, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Huile d'olive", quantite: 100, unite: "ml", categorie: "Condiments" },
      { nom: "Levure chimique", quantite: 8, unite: "g", categorie: "Épicerie" },
      { nom: "Jambon blanc", quantite: 150, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Olives vertes dénoyautées", quantite: 100, unite: "g", categorie: "Épicerie" },
      { nom: "Gruyère râpé", quantite: 100, unite: "g", categorie: "Produits laitiers" },
      { nom: "Sel", quantite: 3, unite: "g", categorie: "Condiments" },
      { nom: "Poivre", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre œufs, lait, huile, sel et poivre dans le bol. Mélanger.", vitesse: 4, duree: 30 },
      { numero: 2, instruction: "Ajouter farine et levure.", vitesse: 6, duree: 30 },
      { numero: 3, instruction: "Couper le jambon en dés, hacher grossièrement les olives. Ajouter avec le gruyère dans le bol.", vitesse: 2, duree: 20, conseil: "Ne pas trop mélanger pour garder les morceaux entiers." },
      { numero: 4, instruction: "Verser dans un moule à cake beurré. Enfourner 45 min à 180°C.", duree: 2700, conseil: "Le cake est cuit quand un cure-dent en ressort sec." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "veloute-potimarron-chataignes-companion",
    titre: "Velouté de potimarron aux châtaignes",
    description: "Un velouté automnal réconfortant, sucré-salé avec ses châtaignes fondantes. La saveur de l'automne en bol.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 25,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["COMPANION"],
    categories: ["soupe", "entree"],
    regime: ["vegetarien", "sans-gluten"],
    tags: ["potimarron", "châtaignes", "automne", "velouté"],
    calories_par_portion: 180,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Potimarron", quantite: 800, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Châtaignes cuites sous vide", quantite: 200, unite: "g", categorie: "Épicerie" },
      { nom: "Oignon", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Bouillon de volaille", quantite: 700, unite: "ml", categorie: "Épicerie" },
      { nom: "Crème liquide", quantite: 100, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Beurre", quantite: 20, unite: "g", categorie: "Produits laitiers" },
      { nom: "Muscade", quantite: 1, unite: "pincée", categorie: "Condiments" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Hacher l'oignon dans le bol.", vitesse: 11, duree: 10 },
      { numero: 2, instruction: "Faire fondre le beurre, ajouter l'oignon. Suer.", vitesse: 1, temperature: 130, duree: 180 },
      { numero: 3, instruction: "Ajouter le potimarron en cubes (avec la peau lavée), 150g de châtaignes et le bouillon.", vitesse: 1, temperature: 100, duree: 1200 },
      { numero: 4, instruction: "Mixer pour obtenir un velouté lisse.", vitesse: 12, duree: 60 },
      { numero: 5, instruction: "Ajouter crème, muscade et sel. Mélanger.", vitesse: 4, duree: 15, conseil: "Garnir avec les châtaignes restantes émiettées." },
    ],
    faq: [
      { question: "Faut-il éplucher le potimarron ?", reponse: "Non, sa peau devient tendre à la cuisson et apporte des fibres. La laver soigneusement suffit." },
    ],
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "dorade-vapeur-citron-companion",
    titre: "Dorade vapeur au citron et thym",
    description: "Un poisson cuit vapeur, parfumé aux herbes et citron. Une préparation healthy en moins de 20 minutes.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 15,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["COMPANION"],
    categories: ["plat"],
    regime: ["sans-gluten", "sans-lactose"],
    tags: ["dorade", "vapeur", "citron", "healthy", "rapide"],
    calories_par_portion: 220,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Filets de dorade", quantite: 4, unite: "pièce", categorie: "Viandes & Poissons" },
      { nom: "Citron jaune", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Thym frais", quantite: 5, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Huile d'olive", quantite: 20, unite: "ml", categorie: "Condiments" },
      { nom: "Eau", quantite: 600, unite: "ml", categorie: "Autre" },
      { nom: "Sel", quantite: 3, unite: "g", categorie: "Condiments" },
      { nom: "Poivre", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Verser l'eau dans le bol." },
      { numero: 2, instruction: "Disposer les filets de dorade dans le panier vapeur. Saler, poivrer, citronner et parsemer de thym." },
      { numero: 3, instruction: "Cuire à la vapeur.", vitesse: 1, temperature: 120, duree: 720, accessoire: "Panier vapeur", conseil: "Le poisson est cuit quand sa chair se détache facilement." },
      { numero: 4, instruction: "Servir arrosé d'huile d'olive, avec des légumes vapeur et du riz." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "tartare-saumon-citron-vert-companion",
    titre: "Tartare de saumon au citron vert",
    description: "Un tartare de saumon frais aux notes asiatiques. Le Companion hache à la perfection sans réduire en purée.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 0,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["COMPANION"],
    categories: ["entree", "aperitif"],
    regime: ["sans-gluten", "sans-lactose"],
    tags: ["tartare", "saumon", "cru", "frais"],
    calories_par_portion: 240,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Filet de saumon ultra-frais", quantite: 500, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Citrons verts", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Huile de sésame", quantite: 10, unite: "ml", categorie: "Condiments" },
      { nom: "Sauce soja", quantite: 15, unite: "ml", categorie: "Condiments" },
      { nom: "Coriandre fraîche", quantite: 10, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Échalote", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Avocat", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Graines de sésame", quantite: 10, unite: "g", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre le saumon en cubes dans le bol.", vitesse: 8, duree: 5, conseil: "Donner 2-3 impulsions courtes max — le saumon doit rester en petits dés, pas en purée." },
      { numero: 2, instruction: "Réserver dans un saladier. Ajouter échalote ciselée, coriandre, jus des citrons verts, sauce soja, huile de sésame.", conseil: "Mélanger délicatement à la cuillère." },
      { numero: 3, instruction: "Réfrigérer 15-30 min.", duree: 1800, conseil: "Plus c'est court, plus c'est cru. Plus c'est long, plus c'est cuit par le citron." },
      { numero: 4, instruction: "Dresser dans des cercles avec l'avocat en dés. Parsemer de graines de sésame.", conseil: "Servir très frais avec des chips de wonton." },
    ],
    faq: [
      { question: "Quel saumon utiliser ?", reponse: "Saumon sashimi grade ou ayant été congelé à -18°C minimum 24h pour éliminer les parasites." },
    ],
    approuve: true,
    publie: true,
    vues: 0,
  },

  // ═══════════════════════════════════════════════════════════
  //                  PETITS APPAREILS (20)
  // ═══════════════════════════════════════════════════════════

  // ─── YAOURTIÈRE (2) ─────────────────────────────────────

  {
    slug: "yaourt-grec-onctueux-yaourtiere",
    titre: "Yaourt grec ultra onctueux",
    description: "Le vrai yaourt grec, dense et crémeux, à faire chez soi. Égouttage long pour la texture parfaite.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 480,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["YAOURTIERE"],
    categories: ["petit-dejeuner", "dessert"],
    regime: ["vegetarien", "sans-gluten"],
    tags: ["yaourt grec", "fait maison", "petit-déjeuner"],
    calories_par_portion: 130,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Lait entier", quantite: 1000, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Yaourt nature au lait entier (ferment)", quantite: 1, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Lait en poudre", quantite: 30, unite: "g", categorie: "Produits laitiers" },
    ],
    etapes: [
      { numero: 1, instruction: "Mélanger le lait, le lait en poudre et le yaourt à 40°C." },
      { numero: 2, instruction: "Verser dans les pots. Programme Yaourt à 42°C pendant 8 heures.", duree: 28800, conseil: "Plus la fermentation est longue, plus le yaourt est acide." },
      { numero: 3, instruction: "Réfrigérer 4 heures." },
      { numero: 4, instruction: "Verser le yaourt dans une étamine fine. Égoutter au frigo 4 à 8 heures selon la consistance souhaitée.", duree: 14400, conseil: "Plus l'égouttage est long, plus le yaourt est dense (façon labneh)." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "fromage-blanc-maison-yaourtiere",
    titre: "Fromage blanc maison",
    description: "Du vrai fromage blanc fermier, lisse et frais. Parfait nature, en pâtisserie ou avec des fruits.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 720,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["YAOURTIERE"],
    categories: ["petit-dejeuner", "dessert"],
    regime: ["vegetarien", "sans-gluten"],
    tags: ["fromage blanc", "fait maison", "petit-déjeuner"],
    calories_par_portion: 90,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Lait entier frais", quantite: 1000, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Présure liquide", quantite: 5, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Yaourt nature (ferment)", quantite: 1, unite: "pièce", categorie: "Produits laitiers" },
    ],
    etapes: [
      { numero: 1, instruction: "Tiédir le lait à 25°C. Ajouter la présure et le yaourt. Mélanger doucement." },
      { numero: 2, instruction: "Verser dans la yaourtière. Programme à 35°C pendant 12 heures.", duree: 43200 },
      { numero: 3, instruction: "Verser dans une faisselle ou un linge fin tendu sur un saladier. Égoutter 6h au frigo.", duree: 21600 },
      { numero: 4, instruction: "Fouetter au fouet à main pour obtenir un fromage blanc lisse, ou laisser en faisselle.", conseil: "Conservation 4 jours au frigo." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  // ─── SOUS-VIDE (2) ──────────────────────────────────────

  {
    slug: "magret-canard-rose-sous-vide",
    titre: "Magret de canard rosé",
    description: "Un magret cuit basse température pour une viande tendre rosée à cœur, puis saisi à la poêle pour la peau croustillante.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 90,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["SOUS_VIDE"],
    categories: ["plat"],
    regime: ["sans-gluten", "sans-lactose"],
    tags: ["magret", "canard", "sous-vide", "basse température"],
    calories_par_portion: 380,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Magrets de canard", quantite: 2, unite: "pièce", categorie: "Viandes & Poissons" },
      { nom: "Thym", quantite: 5, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Ail", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Beurre", quantite: 20, unite: "g", categorie: "Produits laitiers" },
      { nom: "Sel", quantite: 5, unite: "g", categorie: "Condiments" },
      { nom: "Poivre", quantite: 3, unite: "g", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Quadriller la peau du magret au couteau, sans entailler la chair. Saler, poivrer." },
      { numero: 2, instruction: "Mettre les magrets sous vide avec thym, ail écrasé et un peu de beurre." },
      { numero: 3, instruction: "Cuire au sous-vide à 56°C pendant 1h30 (rosé) ou 58°C pour à point.", duree: 5400, conseil: "Pour un magret saignant : 54°C / 1h." },
      { numero: 4, instruction: "Sortir du sac. Saisir côté peau dans une poêle froide. Monter doucement en température, 5-7 min jusqu'à ce que la peau soit dorée et croustillante.", duree: 360 },
      { numero: 5, instruction: "Laisser reposer 5 min. Trancher en biais.", conseil: "Servir avec une sauce au miel et balsamique." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "carottes-glacees-sous-vide",
    titre: "Carottes glacées au miel",
    description: "Des carottes fondantes et brillantes, gardant toute leur saveur grâce à la cuisson sous vide.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 60,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["SOUS_VIDE"],
    categories: ["accompagnement"],
    regime: ["vegetarien", "sans-gluten"],
    tags: ["carottes", "miel", "sous-vide", "accompagnement"],
    calories_par_portion: 110,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Carottes nouvelles", quantite: 600, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Beurre", quantite: 30, unite: "g", categorie: "Produits laitiers" },
      { nom: "Miel", quantite: 20, unite: "g", categorie: "Épicerie" },
      { nom: "Cumin en grains", quantite: 3, unite: "g", categorie: "Condiments" },
      { nom: "Sel", quantite: 3, unite: "g", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Brosser les carottes (ne pas éplucher si elles sont jeunes). Les couper en bâtonnets." },
      { numero: 2, instruction: "Mettre sous vide avec beurre, miel, cumin et sel." },
      { numero: 3, instruction: "Cuire à 85°C pendant 1 heure.", duree: 3600 },
      { numero: 4, instruction: "Ouvrir le sac. Verser le tout dans une poêle. Réduire le jus 2-3 min jusqu'à ce qu'il glace les carottes.", conseil: "Parsemer de persil ciselé avant de servir." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  // ─── SORBETIÈRE (2) ─────────────────────────────────────

  {
    slug: "sorbet-citron-vert-basilic-sorbetiere",
    titre: "Sorbet citron vert et basilic",
    description: "Un sorbet frais et acidulé avec une touche d'herbes fraîches. Idéal en trou normand ou en dessert d'été.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 25,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["SORBETIERE"],
    categories: ["dessert"],
    regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["sorbet", "citron vert", "basilic", "été"],
    calories_par_portion: 110,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Citrons verts (jus + zeste)", quantite: 6, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Sucre", quantite: 150, unite: "g", categorie: "Épicerie" },
      { nom: "Eau", quantite: 400, unite: "ml", categorie: "Autre" },
      { nom: "Basilic frais", quantite: 15, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Blanc d'œuf (optionnel)", quantite: 1, unite: "pièce", categorie: "Produits laitiers" },
    ],
    etapes: [
      { numero: 1, instruction: "Faire un sirop : porter à ébullition l'eau et le sucre 5 min. Hors feu, ajouter le basilic effeuillé. Laisser infuser 30 min couvert.", duree: 1800 },
      { numero: 2, instruction: "Filtrer le sirop. Ajouter le jus et les zestes des citrons verts. Réfrigérer 4h.", duree: 14400, conseil: "Le froid est essentiel pour un bon sorbet." },
      { numero: 3, instruction: "Mettre en sorbetière. Ajouter le blanc d'œuf à mi-turbinage si utilisé (texture plus aérée). Turbiner 25 min.", duree: 1500 },
      { numero: 4, instruction: "Mettre au congélateur 1h pour raffermir avant de servir.", duree: 3600 },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "glace-stracciatella-sorbetiere",
    titre: "Glace stracciatella italienne",
    description: "La glace italienne classique : crème vanille parsemée d'éclats de chocolat noir cassants.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 20,
    temps_cuisson: 30,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["SORBETIERE"],
    categories: ["dessert"],
    regime: ["vegetarien", "sans-gluten"],
    tags: ["glace", "stracciatella", "italien", "chocolat"],
    calories_par_portion: 290,
    nutriscore: "D",
    nutriscore_note: "Riche en sucre et lipides",
    ingredients: [
      { nom: "Lait entier", quantite: 250, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Crème liquide entière", quantite: 250, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Jaunes d'œufs", quantite: 4, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Sucre", quantite: 100, unite: "g", categorie: "Épicerie" },
      { nom: "Gousse de vanille", quantite: 1, unite: "pièce", categorie: "Épicerie" },
      { nom: "Chocolat noir 70%", quantite: 100, unite: "g", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Faire chauffer le lait, la crème et la gousse de vanille fendue jusqu'à frémissement. Couvrir, infuser 15 min." },
      { numero: 2, instruction: "Fouetter les jaunes avec le sucre. Verser le lait chaud en filet en fouettant." },
      { numero: 3, instruction: "Remettre sur feu doux et cuire à 83°C en remuant constamment, jusqu'à napper la spatule (crème anglaise). Filtrer.", conseil: "Ne pas faire bouillir, sinon les œufs coagulent." },
      { numero: 4, instruction: "Réfrigérer 4h.", duree: 14400 },
      { numero: 5, instruction: "Turbiner 25 min en sorbetière. À la fin, faire fondre le chocolat et le verser en filet sur la glace tournante : il se brise en éclats.", duree: 1500, conseil: "Servir avec des amaretti écrasés." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  // ─── MICRO-ONDES (2) ────────────────────────────────────

  {
    slug: "pommes-terre-vapeur-micro-ondes",
    titre: "Pommes de terre vapeur express",
    description: "Des pommes de terre cuites en 8 minutes au micro-ondes, fondantes comme à la vapeur. Le secret : un bol couvert.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 5,
    temps_cuisson: 8,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["MICRO_ONDES"],
    categories: ["accompagnement"],
    regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["pommes de terre", "vapeur", "express", "micro-ondes"],
    calories_par_portion: 130,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Pommes de terre nouvelles", quantite: 600, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Eau", quantite: 50, unite: "ml", categorie: "Autre" },
      { nom: "Beurre", quantite: 20, unite: "g", categorie: "Produits laitiers" },
      { nom: "Persil plat", quantite: 5, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Brosser les pommes de terre. Les couper en 2 si elles sont grosses." },
      { numero: 2, instruction: "Mettre dans un bol micro-ondable avec l'eau. Couvrir d'un film percé ou d'un couvercle adapté." },
      { numero: 3, instruction: "Micro-ondes 8 min à 800W.", duree: 480, conseil: "Vérifier la cuisson avec la pointe d'un couteau, prolonger 1-2 min si besoin." },
      { numero: 4, instruction: "Laisser reposer 2 min. Égoutter. Mélanger avec beurre, persil et sel." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "popcorn-maison-micro-ondes",
    titre: "Pop-corn maison au beurre",
    description: "Le pop-corn de cinéma fait maison au micro-ondes. Plus économique et bien meilleur que les sachets industriels.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 2,
    temps_cuisson: 3,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["MICRO_ONDES"],
    categories: ["aperitif", "dessert"],
    regime: ["vegetarien", "sans-gluten"],
    tags: ["pop-corn", "cinéma", "express", "snack"],
    calories_par_portion: 140,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Maïs à pop-corn", quantite: 80, unite: "g", categorie: "Épicerie" },
      { nom: "Beurre fondu", quantite: 30, unite: "g", categorie: "Produits laitiers" },
      { nom: "Sel fin", quantite: 3, unite: "g", categorie: "Condiments" },
      { nom: "Sucre glace (version sucrée)", quantite: 20, unite: "g", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre le maïs dans un grand bol micro-ondable. Couvrir avec une assiette." },
      { numero: 2, instruction: "Micro-ondes 2-3 min à pleine puissance (1000W). Arrêter dès que les éclatements espacent à plus de 2 secondes.", duree: 180, conseil: "Ne pas attendre que tout soit éclaté, sinon ça brûle." },
      { numero: 3, instruction: "Verser le beurre fondu et le sel. Secouer. Pour version sucrée : sucre glace au lieu de sel." },
    ],
    faq: [
      { question: "Pourquoi mon pop-corn brûle-t-il ?", reponse: "La puissance est trop élevée ou la cuisson trop longue. S'arrêter dès que les pops ralentissent." },
    ],
    approuve: true,
    publie: true,
    vues: 0,
  },

  // ─── INDUCTION (2) ──────────────────────────────────────

  {
    slug: "risotto-safran-induction",
    titre: "Risotto au safran (alla Milanese)",
    description: "Le risotto milanais doré au safran, crémeux et al dente. La régulation précise de l'induction est parfaite pour le risotto.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 25,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["INDUCTION"],
    categories: ["plat"],
    regime: ["vegetarien", "sans-gluten"],
    tags: ["risotto", "safran", "Milan", "italien"],
    calories_par_portion: 420,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Riz Arborio ou Carnaroli", quantite: 320, unite: "g", categorie: "Épicerie" },
      { nom: "Bouillon de volaille", quantite: 1200, unite: "ml", categorie: "Épicerie" },
      { nom: "Vin blanc sec", quantite: 100, unite: "ml", categorie: "Boissons" },
      { nom: "Échalote", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Pistils de safran", quantite: 0.3, unite: "g", categorie: "Condiments" },
      { nom: "Beurre", quantite: 60, unite: "g", categorie: "Produits laitiers" },
      { nom: "Parmesan râpé", quantite: 80, unite: "g", categorie: "Produits laitiers" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Faire infuser le safran dans 100ml de bouillon chaud. Garder le reste du bouillon au chaud (puissance 3)." },
      { numero: 2, instruction: "Faire fondre 30g de beurre dans une sauteuse, induction puissance 5. Faire suer l'échalote ciselée 2 min." },
      { numero: 3, instruction: "Ajouter le riz, nacrer 1 min en remuant. Déglacer au vin blanc. Laisser absorber.", duree: 60 },
      { numero: 4, instruction: "Verser le bouillon louche par louche, en remuant constamment. Cuire 18 min en attendant chaque fois que le liquide soit absorbé.", duree: 1080 },
      { numero: 5, instruction: "Ajouter le bouillon au safran à mi-cuisson. Hors feu, ajouter beurre et parmesan, mantecare (mélanger énergiquement).", conseil: "Le risotto doit être all'onda — coulant comme une vague." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "wok-boeuf-brocoli-induction",
    titre: "Wok de bœuf au brocoli sauce huître",
    description: "Le grand classique sino-américain. La forte puissance de l'induction permet la saisie minute à la mode wok.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 8,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["INDUCTION"],
    categories: ["plat"],
    regime: ["sans-lactose"],
    tags: ["wok", "bœuf", "brocoli", "asiatique", "rapide"],
    calories_par_portion: 320,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Bavette de bœuf", quantite: 400, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Brocoli", quantite: 400, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Sauce huître", quantite: 30, unite: "ml", categorie: "Condiments" },
      { nom: "Sauce soja", quantite: 30, unite: "ml", categorie: "Condiments" },
      { nom: "Ail", quantite: 3, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Gingembre frais", quantite: 15, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Maïzena", quantite: 10, unite: "g", categorie: "Épicerie" },
      { nom: "Huile neutre", quantite: 30, unite: "ml", categorie: "Condiments" },
      { nom: "Huile de sésame", quantite: 5, unite: "ml", categorie: "Condiments" },
      { nom: "Eau", quantite: 100, unite: "ml", categorie: "Autre" },
    ],
    etapes: [
      { numero: 1, instruction: "Couper le bœuf en lanières fines. Mélanger avec maïzena, 1 c. à s. de soja. Réserver 10 min." },
      { numero: 2, instruction: "Blanchir le brocoli en bouquets 2 min dans l'eau bouillante. Égoutter et passer sous l'eau froide." },
      { numero: 3, instruction: "Chauffer le wok à pleine puissance avec l'huile. Saisir le bœuf 1 minute en remuant.", duree: 60 },
      { numero: 4, instruction: "Ajouter ail et gingembre émincés. Sauter 30 secondes." },
      { numero: 5, instruction: "Ajouter le brocoli, sauce huître, soja et eau. Sauter 2-3 minutes. Finir à l'huile de sésame.", duree: 180, conseil: "Servir immédiatement avec du riz blanc." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  // ─── GAUFRIER (1) ───────────────────────────────────────

  {
    slug: "gaufres-salees-jambon-gruyere-gaufrier",
    titre: "Gaufres salées jambon-gruyère",
    description: "Des gaufres apéro salées au jambon et fromage, parfaites pour un brunch ou un buffet.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 15,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["GAUFRIER"],
    categories: ["aperitif", "entree"],
    regime: [],
    tags: ["gaufres salées", "jambon", "fromage", "apéro"],
    calories_par_portion: 320,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Farine", quantite: 250, unite: "g", categorie: "Épicerie" },
      { nom: "Œufs", quantite: 3, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Lait", quantite: 300, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Beurre fondu", quantite: 50, unite: "g", categorie: "Produits laitiers" },
      { nom: "Levure chimique", quantite: 8, unite: "g", categorie: "Épicerie" },
      { nom: "Jambon en dés", quantite: 100, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Gruyère râpé", quantite: 100, unite: "g", categorie: "Produits laitiers" },
      { nom: "Sel", quantite: 3, unite: "g", categorie: "Condiments" },
      { nom: "Poivre", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mélanger farine, œufs, lait et beurre fondu jusqu'à pâte lisse." },
      { numero: 2, instruction: "Incorporer levure, jambon, gruyère, sel et poivre." },
      { numero: 3, instruction: "Cuire 4 min par gaufre dans le gaufrier bien chaud.", duree: 240, conseil: "Servir avec une salade verte ou en mini-bouchées à l'apéro." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  // ─── DÉSHYDRATEUR (2) ───────────────────────────────────

  {
    slug: "fruits-secs-mangue-deshydrateur",
    titre: "Mangue séchée au déshydrateur",
    description: "Des lamelles de mangue séchée, snack sain et naturel. Parfait pour la rando ou le goûter.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 600,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["DESHYDRATEUR"],
    categories: ["dessert", "aperitif"],
    regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["mangue", "fruit séché", "healthy", "snack"],
    calories_par_portion: 110,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Mangues mûres", quantite: 3, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Jus de citron vert", quantite: 15, unite: "ml", categorie: "Fruits & Légumes" },
    ],
    etapes: [
      { numero: 1, instruction: "Éplucher les mangues. Couper en lamelles de 5mm d'épaisseur." },
      { numero: 2, instruction: "Badigeonner légèrement de jus de citron vert (anti-oxydant)." },
      { numero: 3, instruction: "Disposer sur les plateaux sans superposition. Déshydrater à 55°C pendant 8-10h.", duree: 36000, conseil: "La mangue est prête quand elle est souple mais sèche au toucher, pas friable." },
      { numero: 4, instruction: "Conserver dans un bocal hermétique 2-3 mois." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "herbes-aromatiques-deshydrateur",
    titre: "Herbes aromatiques séchées",
    description: "Conservez vos herbes du jardin (basilic, thym, romarin, persil) en les séchant au déshydrateur. Saveur préservée.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 240,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["DESHYDRATEUR"],
    categories: ["accompagnement"],
    regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["herbes", "séchage", "conservation", "jardin"],
    calories_par_portion: 5,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Basilic frais", quantite: 50, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Thym frais", quantite: 50, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Romarin frais", quantite: 50, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Persil plat", quantite: 50, unite: "g", categorie: "Fruits & Légumes" },
    ],
    etapes: [
      { numero: 1, instruction: "Laver les herbes et bien sécher dans un torchon. Détacher les feuilles des tiges (sauf thym et romarin)." },
      { numero: 2, instruction: "Disposer en une couche sur les plateaux du déshydrateur." },
      { numero: 3, instruction: "Déshydrater à 35°C pendant 4 heures (basse température pour préserver les huiles essentielles).", duree: 14400, conseil: "Les herbes sont prêtes quand elles s'effritent entre les doigts." },
      { numero: 4, instruction: "Émietter et conserver dans des bocaux hermétiques à l'abri de la lumière. Se gardent 1 an." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  // ─── CUISEUR VAPEUR (2) ─────────────────────────────────

  {
    slug: "boulettes-vapeur-poulet-cuiseur-vapeur",
    titre: "Boulettes vapeur de poulet au gingembre",
    description: "Des boulettes asiatiques ultra moelleuses, cuites à la vapeur. Servies avec une sauce soja-sésame.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 12,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_VAPEUR"],
    categories: ["plat", "aperitif"],
    regime: ["sans-lactose"],
    tags: ["boulettes", "poulet", "vapeur", "asiatique"],
    calories_par_portion: 240,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Blancs de poulet hachés", quantite: 500, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Gingembre frais râpé", quantite: 15, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Oignon vert", quantite: 3, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Sauce soja", quantite: 20, unite: "ml", categorie: "Condiments" },
      { nom: "Huile de sésame", quantite: 5, unite: "ml", categorie: "Condiments" },
      { nom: "Œuf", quantite: 1, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Chapelure panko", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Coriandre fraîche", quantite: 5, unite: "g", categorie: "Fruits & Légumes" },
    ],
    etapes: [
      { numero: 1, instruction: "Mélanger tous les ingrédients dans un saladier. Bien mélanger 2 minutes pour rendre la farce homogène." },
      { numero: 2, instruction: "Former des boulettes de la taille d'une noix (humidifier les mains pour éviter que ça colle)." },
      { numero: 3, instruction: "Disposer dans le panier vapeur garni de papier sulfurisé. Cuire à la vapeur 100°C pendant 12 min.", duree: 720, conseil: "Les boulettes sont cuites quand elles sont fermes au toucher." },
      { numero: 4, instruction: "Servir avec une sauce trempette : 4 c. à s. soja + 1 c. à s. vinaigre de riz + 1 c. à c. sésame." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "flan-coco-vapeur-cuiseur-vapeur",
    titre: "Petits flans coco vapeur",
    description: "Des flans antillais à la noix de coco, cuits doucement à la vapeur pour une texture parfaitement lisse.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 25,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_VAPEUR"],
    categories: ["dessert"],
    regime: ["vegetarien", "sans-gluten"],
    tags: ["flan", "coco", "antillais", "vapeur"],
    calories_par_portion: 220,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Lait de coco", quantite: 400, unite: "ml", categorie: "Épicerie" },
      { nom: "Œufs", quantite: 4, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Sucre", quantite: 80, unite: "g", categorie: "Épicerie" },
      { nom: "Noix de coco râpée", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Vanille", quantite: 1, unite: "pincée", categorie: "Épicerie" },
      { nom: "Caramel liquide", quantite: 50, unite: "g", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Verser un peu de caramel au fond de chaque ramequin." },
      { numero: 2, instruction: "Fouetter les œufs avec le sucre et la vanille. Ajouter le lait de coco et la noix de coco râpée." },
      { numero: 3, instruction: "Verser dans les ramequins. Couvrir d'aluminium." },
      { numero: 4, instruction: "Cuire à la vapeur 100°C pendant 25 minutes.", duree: 1500, conseil: "Les flans doivent être pris mais légèrement tremblotants au centre." },
      { numero: 5, instruction: "Réfrigérer 4h. Démouler en passant un couteau sur les bords.", duree: 14400 },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  // ─── CUISEUR RIZ (2) ────────────────────────────────────

  {
    slug: "paella-cuiseur-riz",
    titre: "Paella mixte poulet et fruits de mer",
    description: "Une paella valencienne au safran, poulet et crevettes. Le cuiseur à riz fait le travail à votre place.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 20,
    temps_cuisson: 35,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_RIZ"],
    categories: ["plat"],
    regime: ["sans-gluten", "sans-lactose"],
    tags: ["paella", "espagnol", "riz", "fruits de mer"],
    calories_par_portion: 480,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Riz à paella (Bomba ou Calasparra)", quantite: 300, unite: "g", categorie: "Épicerie" },
      { nom: "Cuisses de poulet", quantite: 4, unite: "pièce", categorie: "Viandes & Poissons" },
      { nom: "Crevettes décortiquées", quantite: 200, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Moules", quantite: 200, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Bouillon de volaille", quantite: 700, unite: "ml", categorie: "Épicerie" },
      { nom: "Tomates concassées", quantite: 200, unite: "g", categorie: "Épicerie" },
      { nom: "Poivron rouge", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Petits pois surgelés", quantite: 100, unite: "g", categorie: "Surgelés" },
      { nom: "Oignon", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Ail", quantite: 3, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Pistils de safran", quantite: 0.3, unite: "g", categorie: "Condiments" },
      { nom: "Paprika fumé", quantite: 5, unite: "g", categorie: "Condiments" },
      { nom: "Huile d'olive", quantite: 30, unite: "ml", categorie: "Condiments" },
      { nom: "Citron", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
    ],
    etapes: [
      { numero: 1, instruction: "Faire dorer le poulet dans une poêle à feu vif 5 min de chaque côté avec l'huile. Réserver." },
      { numero: 2, instruction: "Dans la même poêle, faire suer oignon et ail hachés. Ajouter poivron en lanières et tomates. Cuire 5 min." },
      { numero: 3, instruction: "Mettre le riz, le mélange de la poêle, le poulet, le bouillon, le safran et le paprika dans le cuiseur à riz." },
      { numero: 4, instruction: "Programme Riz blanc.", duree: 1800 },
      { numero: 5, instruction: "À 5 minutes de la fin, ajouter crevettes, moules et petits pois sur le dessus. Couvrir.", conseil: "Servir avec des quartiers de citron." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "risotto-courge-cuiseur-riz",
    titre: "Risotto de courge butternut au cuiseur riz",
    description: "Un faux-risotto crémeux à la courge butternut sans surveiller la cuisson. Astuce gain de temps.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 25,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["CUISEUR_RIZ"],
    categories: ["plat"],
    regime: ["vegetarien", "sans-gluten"],
    tags: ["risotto", "courge", "butternut", "automne"],
    calories_par_portion: 380,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Riz Arborio", quantite: 300, unite: "g", categorie: "Épicerie" },
      { nom: "Courge butternut", quantite: 400, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Bouillon de légumes", quantite: 800, unite: "ml", categorie: "Épicerie" },
      { nom: "Oignon", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Vin blanc", quantite: 100, unite: "ml", categorie: "Boissons" },
      { nom: "Beurre", quantite: 40, unite: "g", categorie: "Produits laitiers" },
      { nom: "Parmesan râpé", quantite: 60, unite: "g", categorie: "Produits laitiers" },
      { nom: "Sauge fraîche", quantite: 5, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Couper la courge en cubes de 1 cm. Hacher l'oignon." },
      { numero: 2, instruction: "Mettre tous les ingrédients sauf parmesan et sauge dans le cuiseur à riz." },
      { numero: 3, instruction: "Programme Riz blanc (ou cuisson rapide).", duree: 1500 },
      { numero: 4, instruction: "À la fin, ajouter parmesan et sauge ciselée. Mélanger énergiquement.", conseil: "Pour un effet vraie risotto, écraser un peu de courge à la cuillère." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  // ─── CENTRIFUGEUSE (1) ──────────────────────────────────

  {
    slug: "jus-tomate-celeri-centrifugeuse",
    titre: "Jus de tomate-céleri façon Bloody Mary",
    description: "Un jus de tomate maison épicé au céleri, version cocktail mocktail ou base de Bloody Mary.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 0,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["CENTRIFUGEUSE"],
    categories: ["boisson", "aperitif"],
    regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["jus", "tomate", "céleri", "Bloody Mary"],
    calories_par_portion: 35,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Tomates mûres", quantite: 800, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Branches de céleri", quantite: 4, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Citron", quantite: 0.5, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Sauce Worcestershire", quantite: 10, unite: "ml", categorie: "Condiments" },
      { nom: "Sauce Tabasco", quantite: 1, unite: "pincée", categorie: "Condiments" },
      { nom: "Sel de céleri", quantite: 2, unite: "g", categorie: "Condiments" },
      { nom: "Poivre", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Laver tomates et céleri. Éplucher le citron." },
      { numero: 2, instruction: "Passer les tomates, le céleri et le citron à la centrifugeuse." },
      { numero: 3, instruction: "Ajouter Worcestershire, Tabasco, sel de céleri et poivre. Mélanger.", conseil: "Servir très frais avec une branche de céleri en swizzle stick." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  // ─── BOUILLOIRE (1) ─────────────────────────────────────

  {
    slug: "matcha-latte-bouilloire",
    titre: "Matcha latte au lait d'avoine",
    description: "Le matcha latte du café d'à côté, à faire chez soi pour une fraction du prix. La bouilloire à 80°C est la clé.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 5,
    temps_cuisson: 2,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["BOUILLOIRE"],
    categories: ["boisson", "petit-dejeuner"],
    regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["matcha", "latte", "japonais", "café"],
    calories_par_portion: 110,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Thé matcha en poudre", quantite: 8, unite: "g", categorie: "Épicerie" },
      { nom: "Eau", quantite: 200, unite: "ml", categorie: "Autre" },
      { nom: "Lait d'avoine", quantite: 600, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Sirop d'érable", quantite: 30, unite: "ml", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Chauffer l'eau à 80°C exactement à la bouilloire (jamais bouillante, sinon le matcha devient amer)." },
      { numero: 2, instruction: "Tamiser la poudre de matcha dans un bol. Ajouter 50ml d'eau chaude. Fouetter en zigzag avec un fouet en bambou (chasen) jusqu'à mousse." },
      { numero: 3, instruction: "Faire mousser le lait d'avoine tiède. Sucrer avec le sirop d'érable." },
      { numero: 4, instruction: "Verser le matcha dans des verres, ajouter le lait mousseux par-dessus.", conseil: "Pour un effet art latte, verser le lait en filet en dessinant." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  // ─── BATTEUR SOCLE (1) ──────────────────────────────────

  {
    slug: "tarte-citron-meringuee-batteur",
    titre: "Tarte au citron meringuée",
    description: "La tarte au citron classique avec sa meringue italienne brillante. Le batteur monte la meringue à la perfection.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 40,
    temps_cuisson: 25,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["BATTEUR_SOCLE"],
    categories: ["dessert"],
    regime: ["vegetarien"],
    tags: ["tarte", "citron", "meringue", "français"],
    calories_par_portion: 340,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Pâte sablée", quantite: 1, unite: "pièce", categorie: "Épicerie" },
      { nom: "Citrons jaunes", quantite: 4, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Œufs", quantite: 3, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Sucre", quantite: 150, unite: "g", categorie: "Épicerie" },
      { nom: "Beurre", quantite: 80, unite: "g", categorie: "Produits laitiers" },
      { nom: "Maïzena", quantite: 10, unite: "g", categorie: "Épicerie" },
      { nom: "Blancs d'œufs (meringue)", quantite: 3, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Sucre (meringue italienne)", quantite: 180, unite: "g", categorie: "Épicerie" },
      { nom: "Eau", quantite: 60, unite: "ml", categorie: "Autre" },
    ],
    etapes: [
      { numero: 1, instruction: "Étaler la pâte sablée dans un moule à tarte. Cuire à blanc 15 min à 180°C avec des billes de cuisson.", duree: 900 },
      { numero: 2, instruction: "Lemon curd : fouetter œufs, sucre, jus et zeste des citrons, maïzena. Cuire au bain-marie 10 min en remuant. Hors feu, ajouter le beurre froid.", duree: 600 },
      { numero: 3, instruction: "Verser sur le fond de tarte cuit. Réfrigérer 1h.", duree: 3600 },
      { numero: 4, instruction: "Meringue italienne : cuire le sucre et l'eau à 121°C dans une casserole. Pendant ce temps, monter les blancs en neige au batteur sur socle.", vitesse: 8, accessoire: "fouet ballon" },
      { numero: 5, instruction: "Verser le sirop chaud en filet sur les blancs en fouettant à vitesse moyenne. Continuer jusqu'à refroidissement (8 min).", vitesse: 6, duree: 480 },
      { numero: 6, instruction: "Pocher la meringue sur la tarte. Caraméliser au chalumeau.", conseil: "Servir bien frais." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },
];
