/* =============================================================
   Kitchen Mix — Seed Session 2 : Airfryer + Machine à pain +
                                  Grille-pain + Multicuiseur
   -------------------------------------------------------------
   40 recettes nouvelles (10 par appareil), aucun doublon de slug.

   Pour activer : ajouter dans scripts/seed-mega.ts :
     import { SEED_SESSION_2 } from "../lib/seed-session-2-cuisson";
     ...puis dans ALL_RECIPES, ajouter ...SEED_SESSION_2
   ============================================================= */

import type { SeedRecette } from "./seed-data";

export const SEED_SESSION_2: SeedRecette[] = [

  // ═══════════════════════════════════════════════════════════
  //                    AIRFRYER (10)
  // ═══════════════════════════════════════════════════════════

  {
    slug: "churros-cannelle-airfryer",
    titre: "Churros à la cannelle",
    description: "Les churros espagnols croustillants, version sans bain de friture. Saupoudrés de sucre cannelle, irrésistibles.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 12,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["AIRFRYER"],
    categories: ["dessert"],
    regime: ["vegetarien"],
    tags: ["churros", "espagnol", "cannelle", "goûter"],
    calories_par_portion: 280,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Eau", quantite: 250, unite: "ml", categorie: "Autre" },
      { nom: "Beurre", quantite: 60, unite: "g", categorie: "Produits laitiers" },
      { nom: "Farine", quantite: 150, unite: "g", categorie: "Épicerie" },
      { nom: "Œufs", quantite: 3, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Sucre", quantite: 50, unite: "g", categorie: "Épicerie" },
      { nom: "Cannelle moulue", quantite: 5, unite: "g", categorie: "Condiments" },
      { nom: "Sel", quantite: 2, unite: "g", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Porter l'eau, le beurre et le sel à ébullition. Hors feu, ajouter la farine d'un coup et mélanger énergiquement." },
      { numero: 2, instruction: "Incorporer les œufs un par un. La pâte doit être lisse et brillante." },
      { numero: 3, instruction: "Mettre dans une poche à douille cannelée. Coucher des bâtonnets de 10 cm sur du papier sulfurisé." },
      { numero: 4, instruction: "Airfryer 12 min à 180°C, en plusieurs fournées sans superposer.", duree: 720 },
      { numero: 5, instruction: "Rouler les churros chauds dans le mélange sucre + cannelle.", conseil: "Servir avec une sauce chocolat fondu pour tremper." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "donuts-glaces-airfryer",
    titre: "Donuts glacés rapides",
    description: "Des donuts moelleux glacés sucre, version santé sans friture. Prêts en 15 minutes total.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 8,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["AIRFRYER"],
    categories: ["dessert", "petit-dejeuner"],
    regime: ["vegetarien"],
    tags: ["donuts", "américain", "goûter"],
    calories_par_portion: 240,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Pâte à pizza prête", quantite: 1, unite: "pièce", categorie: "Épicerie" },
      { nom: "Sucre glace", quantite: 100, unite: "g", categorie: "Épicerie" },
      { nom: "Lait", quantite: 30, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Vanille", quantite: 5, unite: "ml", categorie: "Épicerie" },
      { nom: "Vermicelles colorés", quantite: 20, unite: "g", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Étaler la pâte. Découper des cercles à l'emporte-pièce, puis un trou central avec un verre à liqueur." },
      { numero: 2, instruction: "Airfryer 8 min à 175°C.", duree: 480 },
      { numero: 3, instruction: "Mélanger sucre glace, lait et vanille pour le glaçage. Tremper le dessus des donuts encore tièdes. Saupoudrer de vermicelles." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "pommes-noisettes-airfryer",
    titre: "Pommes noisettes croustillantes",
    description: "Les pommes noisettes des cantines, version maison à l'airfryer. Croustillantes dehors, fondantes dedans.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 18,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["AIRFRYER"],
    categories: ["accompagnement"],
    regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["pommes noisettes", "airfryer", "enfant"],
    calories_par_portion: 180,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Pommes de terre", quantite: 700, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Fécule de maïs", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Huile", quantite: 15, unite: "ml", categorie: "Condiments" },
      { nom: "Sel", quantite: 5, unite: "g", categorie: "Condiments" },
      { nom: "Muscade", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Cuire les pommes de terre 20 min à l'eau. Égoutter, écraser à la fourchette." },
      { numero: 2, instruction: "Mélanger avec fécule, sel, muscade. Former des petites boulettes en forme de noisette." },
      { numero: 3, instruction: "Vaporiser d'huile. Airfryer 18 min à 200°C en remuant à mi-cuisson.", duree: 1080 },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "brownies-airfryer",
    titre: "Brownies fondants au chocolat",
    description: "Des brownies fondants cuits à l'airfryer en 20 minutes. Cœur tendre, croûte craquante.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 20,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["AIRFRYER"],
    categories: ["dessert"],
    regime: ["vegetarien"],
    tags: ["brownies", "chocolat", "fondant"],
    calories_par_portion: 360,
    nutriscore: "D",
    nutriscore_note: "Riche en sucre et lipides",
    ingredients: [
      { nom: "Chocolat noir", quantite: 200, unite: "g", categorie: "Épicerie" },
      { nom: "Beurre", quantite: 150, unite: "g", categorie: "Produits laitiers" },
      { nom: "Sucre", quantite: 150, unite: "g", categorie: "Épicerie" },
      { nom: "Œufs", quantite: 3, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Farine", quantite: 80, unite: "g", categorie: "Épicerie" },
      { nom: "Noix de pécan", quantite: 80, unite: "g", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Faire fondre chocolat et beurre. Ajouter sucre, œufs, farine, puis les noix." },
      { numero: 2, instruction: "Verser dans un moule carré chemisé adapté à l'airfryer." },
      { numero: 3, instruction: "Airfryer 20 min à 160°C.", duree: 1200, conseil: "Le brownie doit trembler au centre. Il finit de cuire en refroidissant." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "crevettes-tempura-airfryer",
    titre: "Crevettes tempura croustillantes",
    description: "Des crevettes en tempura japonaise, croustillantes sans bain d'huile. Version healthy et rapide.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 8,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["AIRFRYER"],
    categories: ["aperitif", "plat"],
    regime: ["sans-lactose"],
    tags: ["crevettes", "tempura", "japonais", "rapide"],
    calories_par_portion: 220,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Crevettes décortiquées", quantite: 400, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Farine", quantite: 80, unite: "g", categorie: "Épicerie" },
      { nom: "Eau gazeuse glacée", quantite: 120, unite: "ml", categorie: "Boissons" },
      { nom: "Œuf", quantite: 1, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Chapelure panko", quantite: 80, unite: "g", categorie: "Épicerie" },
      { nom: "Sel", quantite: 3, unite: "g", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mélanger farine, œuf et eau gazeuse glacée pour la pâte tempura. Ne pas trop mélanger." },
      { numero: 2, instruction: "Tremper chaque crevette dans la pâte, puis dans la chapelure panko." },
      { numero: 3, instruction: "Vaporiser d'huile. Airfryer 8 min à 200°C.", duree: 480, conseil: "Servir avec une sauce soja-gingembre ou aïoli." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "tofu-croustillant-airfryer",
    titre: "Tofu croustillant sauce sésame",
    description: "Des cubes de tofu dorés et croustillants, parfait pour bowl asiatique ou en alternative aux nuggets.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 15,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["AIRFRYER"],
    categories: ["plat"],
    regime: ["vegan", "sans-lactose"],
    tags: ["tofu", "vegan", "asiatique", "rapide"],
    calories_par_portion: 230,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Tofu ferme", quantite: 400, unite: "g", categorie: "Épicerie" },
      { nom: "Sauce soja", quantite: 30, unite: "ml", categorie: "Condiments" },
      { nom: "Maïzena", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Huile de sésame", quantite: 10, unite: "ml", categorie: "Condiments" },
      { nom: "Graines de sésame", quantite: 15, unite: "g", categorie: "Épicerie" },
      { nom: "Ail en poudre", quantite: 3, unite: "g", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Presser le tofu 30 min sous un poids pour évacuer l'eau. Couper en cubes de 2 cm." },
      { numero: 2, instruction: "Mariner 10 min avec sauce soja et huile de sésame. Égoutter et enrober de maïzena + ail en poudre." },
      { numero: 3, instruction: "Airfryer 15 min à 200°C en secouant le panier 2 fois.", duree: 900 },
      { numero: 4, instruction: "Saupoudrer de graines de sésame avant de servir.", conseil: "Délicieux dans un bowl avec riz, edamame et crudités." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "cordon-bleu-maison-airfryer",
    titre: "Cordon bleu maison",
    description: "Le cordon bleu fait maison, croustillant et fondant à l'intérieur. Plus sain que la version industrielle.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 14,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["AIRFRYER"],
    categories: ["plat"],
    regime: [],
    tags: ["cordon bleu", "poulet", "fromage"],
    calories_par_portion: 380,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Escalopes de poulet", quantite: 4, unite: "pièce", categorie: "Viandes & Poissons" },
      { nom: "Tranches de jambon", quantite: 4, unite: "pièce", categorie: "Viandes & Poissons" },
      { nom: "Tranches d'emmental", quantite: 4, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Farine", quantite: 50, unite: "g", categorie: "Épicerie" },
      { nom: "Œufs", quantite: 2, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Chapelure", quantite: 100, unite: "g", categorie: "Épicerie" },
      { nom: "Sel", quantite: 3, unite: "g", categorie: "Condiments" },
      { nom: "Poivre", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Aplatir les escalopes au rouleau. Saler, poivrer." },
      { numero: 2, instruction: "Sur chaque escalope, poser une tranche de jambon et une d'emmental. Replier en deux et bien sceller les bords." },
      { numero: 3, instruction: "Paner : farine → œuf battu → chapelure. Vaporiser d'huile." },
      { numero: 4, instruction: "Airfryer 14 min à 190°C en retournant à mi-cuisson.", duree: 840 },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "patates-douces-rotis-airfryer",
    titre: "Patates douces rôties au paprika fumé",
    description: "Des cubes de patate douce caramélisés au paprika fumé. Accompagnement savoureux et coloré.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 18,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["AIRFRYER"],
    categories: ["accompagnement"],
    regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["patate douce", "paprika", "rapide", "healthy"],
    calories_par_portion: 140,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Patates douces", quantite: 700, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Huile d'olive", quantite: 20, unite: "ml", categorie: "Condiments" },
      { nom: "Paprika fumé", quantite: 5, unite: "g", categorie: "Condiments" },
      { nom: "Cumin moulu", quantite: 3, unite: "g", categorie: "Condiments" },
      { nom: "Sel", quantite: 3, unite: "g", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Éplucher les patates douces. Couper en cubes de 2 cm." },
      { numero: 2, instruction: "Mélanger avec huile, paprika fumé, cumin et sel." },
      { numero: 3, instruction: "Airfryer 18 min à 200°C en secouant à mi-cuisson.", duree: 1080 },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "cookies-rapides-airfryer",
    titre: "Cookies express en 8 minutes",
    description: "Des cookies maison en 8 minutes chrono à l'airfryer. Idéal pour quand l'envie de sucré est urgente.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 8,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["AIRFRYER"],
    categories: ["dessert"],
    regime: ["vegetarien"],
    tags: ["cookies", "rapide", "express"],
    calories_par_portion: 280,
    nutriscore: "D",
    nutriscore_note: "Riche en sucre",
    ingredients: [
      { nom: "Beurre fondu", quantite: 100, unite: "g", categorie: "Produits laitiers" },
      { nom: "Sucre roux", quantite: 100, unite: "g", categorie: "Épicerie" },
      { nom: "Œuf", quantite: 1, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Farine", quantite: 200, unite: "g", categorie: "Épicerie" },
      { nom: "Levure chimique", quantite: 3, unite: "g", categorie: "Épicerie" },
      { nom: "Pépites de chocolat", quantite: 100, unite: "g", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Mélanger tous les ingrédients dans un saladier." },
      { numero: 2, instruction: "Former 8 boules. Aplatir légèrement sur du papier sulfurisé." },
      { numero: 3, instruction: "Airfryer 8 min à 170°C en plusieurs fournées.", duree: 480, conseil: "Sortir quand le centre est encore mou — ils durcissent en refroidissant." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "saumon-teriyaki-airfryer",
    titre: "Saumon teriyaki glacé",
    description: "Des pavés de saumon laqués sauce teriyaki, cuisson parfaite à cœur en 10 minutes.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 10,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["AIRFRYER"],
    categories: ["plat"],
    regime: ["sans-gluten", "sans-lactose"],
    tags: ["saumon", "teriyaki", "japonais", "rapide"],
    calories_par_portion: 320,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Pavés de saumon", quantite: 4, unite: "pièce", categorie: "Viandes & Poissons" },
      { nom: "Sauce soja", quantite: 60, unite: "ml", categorie: "Condiments" },
      { nom: "Mirin", quantite: 30, unite: "ml", categorie: "Condiments" },
      { nom: "Miel", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Gingembre frais", quantite: 10, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Graines de sésame", quantite: 10, unite: "g", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Mélanger soja, mirin, miel et gingembre râpé. Mariner le saumon 15 min." },
      { numero: 2, instruction: "Airfryer 10 min à 180°C, badigeonner de marinade à mi-cuisson.", duree: 600 },
      { numero: 3, instruction: "Parsemer de graines de sésame.", conseil: "Servir sur un riz vapeur avec des edamame." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  // ═══════════════════════════════════════════════════════════
  //                 MACHINE À PAIN (10)
  // ═══════════════════════════════════════════════════════════

  {
    slug: "pain-complet-graines-machine",
    titre: "Pain complet aux graines",
    description: "Un pain complet riche en fibres, aux graines de tournesol, courge et lin. Programme Complet.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 5,
    temps_cuisson: 180,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["MACHINE_PAIN"],
    categories: ["boulangerie"],
    regime: ["vegan"],
    tags: ["pain complet", "graines", "fibres", "machine à pain"],
    calories_par_portion: 280,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Farine complète T150", quantite: 350, unite: "g", categorie: "Épicerie" },
      { nom: "Farine T55", quantite: 150, unite: "g", categorie: "Épicerie" },
      { nom: "Eau tiède", quantite: 320, unite: "ml", categorie: "Autre" },
      { nom: "Levure boulangère", quantite: 7, unite: "g", categorie: "Épicerie" },
      { nom: "Graines de tournesol", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Graines de courge", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Graines de lin", quantite: 20, unite: "g", categorie: "Épicerie" },
      { nom: "Sel", quantite: 9, unite: "g", categorie: "Condiments" },
      { nom: "Huile d'olive", quantite: 20, unite: "ml", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre les ingrédients dans la cuve dans l'ordre : eau, huile, sel, farines, graines, levure (bien séparer la levure du sel et de l'eau)." },
      { numero: 2, instruction: "Programme Complet, croûte foncée, poids 1kg.", duree: 10800, conseil: "Démouler dès la fin du programme et laisser refroidir sur une grille." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "pain-mie-toast-machine",
    titre: "Pain de mie pour toast",
    description: "Un pain de mie ultra moelleux, parfait pour les toasts du petit-déjeuner et les sandwichs.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 5,
    temps_cuisson: 180,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["MACHINE_PAIN"],
    categories: ["boulangerie", "petit-dejeuner"],
    regime: ["vegetarien"],
    tags: ["pain de mie", "toast", "moelleux", "machine à pain"],
    calories_par_portion: 250,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Farine T55", quantite: 500, unite: "g", categorie: "Épicerie" },
      { nom: "Lait tiède", quantite: 300, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Beurre mou", quantite: 40, unite: "g", categorie: "Produits laitiers" },
      { nom: "Sucre", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Sel", quantite: 8, unite: "g", categorie: "Condiments" },
      { nom: "Levure boulangère", quantite: 7, unite: "g", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre tous les ingrédients dans la cuve : lait, beurre, sucre, sel, farine, levure." },
      { numero: 2, instruction: "Programme Pain de mie ou Pain sucré, croûte claire, 1kg.", duree: 10800, conseil: "Pour des tranches plus fines, trancher quand il est totalement froid." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "pain-olives-tomates-machine",
    titre: "Pain méditerranéen olives-tomates",
    description: "Un pain savoureux aux olives noires et tomates séchées, parfumé à l'origan. Idéal pour l'apéro ou avec une salade.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 5,
    temps_cuisson: 180,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["MACHINE_PAIN"],
    categories: ["boulangerie", "aperitif"],
    regime: ["vegan"],
    tags: ["pain", "olives", "tomates séchées", "méditerranéen"],
    calories_par_portion: 270,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Farine T65", quantite: 500, unite: "g", categorie: "Épicerie" },
      { nom: "Eau tiède", quantite: 300, unite: "ml", categorie: "Autre" },
      { nom: "Olives noires dénoyautées", quantite: 80, unite: "g", categorie: "Épicerie" },
      { nom: "Tomates séchées", quantite: 60, unite: "g", categorie: "Épicerie" },
      { nom: "Huile d'olive", quantite: 30, unite: "ml", categorie: "Condiments" },
      { nom: "Origan séché", quantite: 5, unite: "g", categorie: "Condiments" },
      { nom: "Sel", quantite: 9, unite: "g", categorie: "Condiments" },
      { nom: "Levure", quantite: 7, unite: "g", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre eau, huile, sel, farine, origan et levure dans la cuve." },
      { numero: 2, instruction: "Lancer Programme Classique. Ajouter olives et tomates séchées hachées au signal sonore (ou en début de pétrissage si pas de bip)." },
      { numero: 3, instruction: "Programme Classique 1kg, croûte moyenne.", duree: 10800 },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "baguette-tradition-machine",
    titre: "Baguette tradition (pâte machine)",
    description: "La machine à pain pétrit la pâte, vous formez et cuisez les baguettes au four pour une vraie croûte croustillante.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 20,
    temps_cuisson: 25,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["MACHINE_PAIN"],
    categories: ["boulangerie"],
    regime: ["vegan"],
    tags: ["baguette", "tradition", "français"],
    calories_par_portion: 230,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Farine T65", quantite: 500, unite: "g", categorie: "Épicerie" },
      { nom: "Eau tiède", quantite: 320, unite: "ml", categorie: "Autre" },
      { nom: "Sel", quantite: 9, unite: "g", categorie: "Condiments" },
      { nom: "Levure boulangère", quantite: 5, unite: "g", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre les ingrédients dans la cuve. Programme Pâte (1h30 environ).", duree: 5400 },
      { numero: 2, instruction: "Diviser la pâte en 3. Former des baguettes longues sur un linge fariné. Lever 30 min.", duree: 1800 },
      { numero: 3, instruction: "Inciser le dessus en biais. Enfourner avec un ramequin d'eau bouillante au fond du four à 240°C, 18-20 min.", duree: 1080, conseil: "La vapeur est essentielle pour la croûte croustillante." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "pain-cereales-machine",
    titre: "Pain aux 5 céréales",
    description: "Un pain rustique aux céréales variées : son, avoine, seigle, millet et tournesol. Riche et nourrissant.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 5,
    temps_cuisson: 180,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["MACHINE_PAIN"],
    categories: ["boulangerie"],
    regime: ["vegan"],
    tags: ["pain", "céréales", "rustique", "fibres"],
    calories_par_portion: 270,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Farine de blé T80", quantite: 350, unite: "g", categorie: "Épicerie" },
      { nom: "Farine de seigle", quantite: 100, unite: "g", categorie: "Épicerie" },
      { nom: "Flocons d'avoine", quantite: 50, unite: "g", categorie: "Épicerie" },
      { nom: "Son de blé", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Graines de millet", quantite: 20, unite: "g", categorie: "Épicerie" },
      { nom: "Graines de tournesol", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Eau", quantite: 350, unite: "ml", categorie: "Autre" },
      { nom: "Sel", quantite: 9, unite: "g", categorie: "Condiments" },
      { nom: "Levure", quantite: 7, unite: "g", categorie: "Épicerie" },
      { nom: "Miel", quantite: 15, unite: "g", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre les ingrédients dans la cuve dans l'ordre prescrit par votre machine." },
      { numero: 2, instruction: "Programme Complet ou Multi-céréales, 1kg, croûte foncée.", duree: 10800 },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "pain-sans-gluten-machine",
    titre: "Pain sans gluten au sarrasin",
    description: "Un pain moelleux sans gluten à base de farines de riz, sarrasin et fécule. Programme dédié.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 5,
    temps_cuisson: 120,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["MACHINE_PAIN"],
    categories: ["boulangerie"],
    regime: ["sans-gluten", "vegan"],
    tags: ["pain", "sans gluten", "sarrasin"],
    calories_par_portion: 250,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Farine de riz", quantite: 250, unite: "g", categorie: "Épicerie" },
      { nom: "Farine de sarrasin", quantite: 150, unite: "g", categorie: "Épicerie" },
      { nom: "Fécule de maïs", quantite: 100, unite: "g", categorie: "Épicerie" },
      { nom: "Gomme de xanthane", quantite: 8, unite: "g", categorie: "Épicerie" },
      { nom: "Eau tiède", quantite: 380, unite: "ml", categorie: "Autre" },
      { nom: "Œufs", quantite: 2, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Huile", quantite: 30, unite: "ml", categorie: "Condiments" },
      { nom: "Vinaigre de cidre", quantite: 10, unite: "ml", categorie: "Condiments" },
      { nom: "Sel", quantite: 8, unite: "g", categorie: "Condiments" },
      { nom: "Levure", quantite: 8, unite: "g", categorie: "Épicerie" },
      { nom: "Sucre", quantite: 15, unite: "g", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Mélanger d'abord les ingrédients liquides dans la cuve, puis ajouter les secs." },
      { numero: 2, instruction: "Programme Sans gluten, 1kg, croûte moyenne.", duree: 7200, conseil: "La pâte est plus liquide qu'une pâte classique : c'est normal." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "pain-chocolat-machine",
    titre: "Pain au chocolat (façon brioche)",
    description: "Un pain brioché aux pépites de chocolat, parfait pour le goûter des enfants. Programme Pain sucré.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 5,
    temps_cuisson: 180,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["MACHINE_PAIN"],
    categories: ["boulangerie", "petit-dejeuner", "dessert"],
    regime: ["vegetarien"],
    tags: ["pain", "chocolat", "goûter", "enfant"],
    calories_par_portion: 320,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Farine T45", quantite: 400, unite: "g", categorie: "Épicerie" },
      { nom: "Lait tiède", quantite: 200, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Beurre mou", quantite: 60, unite: "g", categorie: "Produits laitiers" },
      { nom: "Œufs", quantite: 2, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Sucre", quantite: 60, unite: "g", categorie: "Épicerie" },
      { nom: "Sel", quantite: 5, unite: "g", categorie: "Condiments" },
      { nom: "Levure", quantite: 7, unite: "g", categorie: "Épicerie" },
      { nom: "Pépites de chocolat", quantite: 100, unite: "g", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre les ingrédients dans la cuve sauf les pépites." },
      { numero: 2, instruction: "Programme Pain sucré ou Brioche. Ajouter les pépites au signal (sinon en fin de premier pétrissage).", duree: 10800 },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "pizza-dough-machine",
    titre: "Pâte à pizza italienne",
    description: "La pâte à pizza pétrie sans effort. Programme Pâte de la machine à pain. Étalez et garnissez selon vos envies.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 12,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["MACHINE_PAIN"],
    categories: ["plat", "boulangerie"],
    regime: ["vegan"],
    tags: ["pizza", "pâte", "italien"],
    calories_par_portion: 380,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Farine 00 ou T55", quantite: 500, unite: "g", categorie: "Épicerie" },
      { nom: "Eau tiède", quantite: 300, unite: "ml", categorie: "Autre" },
      { nom: "Huile d'olive", quantite: 30, unite: "ml", categorie: "Condiments" },
      { nom: "Sel", quantite: 10, unite: "g", categorie: "Condiments" },
      { nom: "Levure", quantite: 5, unite: "g", categorie: "Épicerie" },
      { nom: "Sucre", quantite: 5, unite: "g", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Tous les ingrédients dans la cuve. Programme Pâte (1h30 environ).", duree: 5400 },
      { numero: 2, instruction: "Diviser en 4. Étaler finement sur du papier sulfurisé. Garnir." },
      { numero: 3, instruction: "Cuire 10-12 min à 250°C four bien chaud (pierre à pizza idéal).", duree: 720 },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "confiture-fraise-machine",
    titre: "Confiture de fraises maison",
    description: "Une confiture de fraises onctueuse en programme dédié. Pas besoin de surveiller, la machine s'occupe de tout.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 75,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["MACHINE_PAIN"],
    categories: ["dessert", "petit-dejeuner"],
    regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["confiture", "fraises", "été"],
    calories_par_portion: 180,
    nutriscore: "C",
    nutriscore_note: "Riche en sucre",
    ingredients: [
      { nom: "Fraises", quantite: 600, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Sucre cristallisé", quantite: 400, unite: "g", categorie: "Épicerie" },
      { nom: "Jus de citron", quantite: 30, unite: "ml", categorie: "Fruits & Légumes" },
      { nom: "Pectine (optionnel)", quantite: 5, unite: "g", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Équeuter les fraises et les couper en 2 ou 4 selon la taille." },
      { numero: 2, instruction: "Mettre tous les ingrédients dans la cuve." },
      { numero: 3, instruction: "Programme Confiture (généralement 1h15).", duree: 4500, conseil: "Verser chaud dans des pots stérilisés. Retourner les pots pour faire le vide d'air." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "pain-aux-raisins-machine",
    titre: "Pain aux raisins et cannelle",
    description: "Un pain brioché aux raisins secs et cannelle, parfumé et moelleux. Idéal pour le petit-déjeuner.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 5,
    temps_cuisson: 180,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["MACHINE_PAIN"],
    categories: ["boulangerie", "petit-dejeuner"],
    regime: ["vegetarien"],
    tags: ["pain", "raisins", "cannelle", "petit-déjeuner"],
    calories_par_portion: 290,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Farine T55", quantite: 450, unite: "g", categorie: "Épicerie" },
      { nom: "Lait tiède", quantite: 250, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Beurre mou", quantite: 50, unite: "g", categorie: "Produits laitiers" },
      { nom: "Œuf", quantite: 1, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Sucre", quantite: 60, unite: "g", categorie: "Épicerie" },
      { nom: "Sel", quantite: 5, unite: "g", categorie: "Condiments" },
      { nom: "Levure", quantite: 7, unite: "g", categorie: "Épicerie" },
      { nom: "Raisins secs", quantite: 100, unite: "g", categorie: "Épicerie" },
      { nom: "Cannelle moulue", quantite: 5, unite: "g", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Tremper les raisins dans de l'eau tiède 10 min. Égoutter." },
      { numero: 2, instruction: "Ingrédients (sauf raisins) dans la cuve. Programme Pain sucré." },
      { numero: 3, instruction: "Ajouter les raisins au signal sonore.", duree: 10800 },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  // ═══════════════════════════════════════════════════════════
  //                 GRILLE-PAIN (10)
  // ═══════════════════════════════════════════════════════════

  {
    slug: "tartines-fromage-figues-grille-pain",
    titre: "Tartines chèvre, miel et figues",
    description: "Des tartines gourmandes au chèvre fondu, miel et figues fraîches. Servies grillées au pain de campagne.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 5,
    temps_cuisson: 4,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["GRILLE_PAIN"],
    categories: ["entree", "aperitif"],
    regime: ["vegetarien"],
    tags: ["tartines", "chèvre", "figues", "automne"],
    calories_par_portion: 240,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Pain de campagne", quantite: 4, unite: "tranche", categorie: "Boulangerie" },
      { nom: "Chèvre frais (bûche)", quantite: 150, unite: "g", categorie: "Produits laitiers" },
      { nom: "Figues fraîches", quantite: 4, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Miel", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Romarin frais", quantite: 3, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Poivre", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Griller les tranches de pain au grille-pain." },
      { numero: 2, instruction: "Garnir de tranches de chèvre. Passer au grill du four 2 min pour faire fondre.", duree: 120 },
      { numero: 3, instruction: "Disposer des quartiers de figue, arroser de miel, parsemer de romarin et poivre." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "pain-perdu-grille-pain",
    titre: "Pain perdu façon french toast",
    description: "Du pain rassis transformé en dessert moelleux. Le pain est trempé puis grillé pour une cuisson rapide.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 5,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["GRILLE_PAIN"],
    categories: ["dessert", "petit-dejeuner"],
    regime: ["vegetarien"],
    tags: ["pain perdu", "french toast", "petit-déjeuner"],
    calories_par_portion: 290,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Pain de campagne rassis", quantite: 8, unite: "tranche", categorie: "Boulangerie" },
      { nom: "Œufs", quantite: 3, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Lait", quantite: 200, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Sucre", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Vanille", quantite: 5, unite: "ml", categorie: "Épicerie" },
      { nom: "Beurre", quantite: 30, unite: "g", categorie: "Produits laitiers" },
      { nom: "Sirop d'érable", quantite: 60, unite: "ml", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Mélanger œufs, lait, sucre et vanille dans une assiette creuse." },
      { numero: 2, instruction: "Tremper les tranches 10 secondes par face." },
      { numero: 3, instruction: "Faire fondre le beurre dans une poêle. Cuire les tartines 2 min par face jusqu'à dorure.", duree: 240, conseil: "Servir avec sirop d'érable, sucre glace ou fruits frais." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "tartines-saumon-fume-aneth-grille-pain",
    titre: "Tartines saumon fumé et aneth",
    description: "Des toasts élégants au saumon fumé, fromage frais et aneth. Parfait pour brunch ou apéro chic.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 8,
    temps_cuisson: 3,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["GRILLE_PAIN"],
    categories: ["aperitif", "entree", "petit-dejeuner"],
    regime: [],
    tags: ["saumon fumé", "aneth", "brunch", "apéro"],
    calories_par_portion: 220,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Pain de seigle", quantite: 4, unite: "tranche", categorie: "Boulangerie" },
      { nom: "Saumon fumé", quantite: 150, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Fromage frais (Philadelphia)", quantite: 100, unite: "g", categorie: "Produits laitiers" },
      { nom: "Aneth frais", quantite: 5, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Citron", quantite: 0.5, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Câpres", quantite: 15, unite: "g", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Griller les tranches de pain de seigle." },
      { numero: 2, instruction: "Tartiner de fromage frais. Disposer le saumon fumé." },
      { numero: 3, instruction: "Parsemer d'aneth, câpres et zeste de citron. Arroser d'un filet de jus de citron." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "crostini-pesto-mozzarella-grille-pain",
    titre: "Crostini au pesto et mozzarella",
    description: "Des bouchées italiennes : pain grillé, pesto basilic, mozzarella et tomates cerises. Apéro express.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 3,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["GRILLE_PAIN"],
    categories: ["aperitif"],
    regime: ["vegetarien"],
    tags: ["crostini", "pesto", "italien", "apéro"],
    calories_par_portion: 200,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Baguette ou ciabatta", quantite: 1, unite: "pièce", categorie: "Boulangerie" },
      { nom: "Pesto basilic", quantite: 80, unite: "g", categorie: "Épicerie" },
      { nom: "Mozzarella di bufala", quantite: 150, unite: "g", categorie: "Produits laitiers" },
      { nom: "Tomates cerises", quantite: 200, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Basilic frais", quantite: 5, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Huile d'olive", quantite: 10, unite: "ml", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Trancher le pain en biais. Griller au grille-pain." },
      { numero: 2, instruction: "Tartiner de pesto. Ajouter une tranche de mozzarella et 1-2 demi-tomates cerises." },
      { numero: 3, instruction: "Décorer d'une feuille de basilic. Filet d'huile d'olive." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "tartine-banane-cacahuete-grille-pain",
    titre: "Tartine banane et beurre de cacahuète",
    description: "Le snack parfait des sportifs : pain complet grillé, beurre de cacahuète et banane. Énergie longue durée.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 5,
    temps_cuisson: 3,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["GRILLE_PAIN"],
    categories: ["petit-dejeuner", "dessert"],
    regime: ["vegan", "sans-lactose"],
    tags: ["banane", "cacahuète", "petit-déjeuner", "sport"],
    calories_par_portion: 280,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Pain complet", quantite: 4, unite: "tranche", categorie: "Boulangerie" },
      { nom: "Beurre de cacahuète nature", quantite: 100, unite: "g", categorie: "Épicerie" },
      { nom: "Bananes", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Miel ou sirop d'érable", quantite: 20, unite: "g", categorie: "Épicerie" },
      { nom: "Cannelle", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Griller le pain complet." },
      { numero: 2, instruction: "Tartiner généreusement de beurre de cacahuète." },
      { numero: 3, instruction: "Disposer des rondelles de banane. Arroser de miel et saupoudrer de cannelle." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "tartine-thon-tomate-grille-pain",
    titre: "Tartine thon-tomate à la provençale",
    description: "Des tartines fraîches et savoureuses au thon, tomates, anchois et olives. Saveurs du Sud.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 3,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["GRILLE_PAIN"],
    categories: ["entree", "plat"],
    regime: ["sans-lactose"],
    tags: ["thon", "tomate", "provençal", "rapide"],
    calories_par_portion: 230,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Pain de campagne", quantite: 4, unite: "tranche", categorie: "Boulangerie" },
      { nom: "Thon en boîte", quantite: 200, unite: "g", categorie: "Épicerie" },
      { nom: "Tomates", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Anchois à l'huile", quantite: 8, unite: "pièce", categorie: "Viandes & Poissons" },
      { nom: "Olives noires", quantite: 50, unite: "g", categorie: "Épicerie" },
      { nom: "Câpres", quantite: 15, unite: "g", categorie: "Condiments" },
      { nom: "Huile d'olive", quantite: 15, unite: "ml", categorie: "Condiments" },
      { nom: "Basilic frais", quantite: 5, unite: "g", categorie: "Fruits & Légumes" },
    ],
    etapes: [
      { numero: 1, instruction: "Griller les tranches de pain. Frotter avec une gousse d'ail." },
      { numero: 2, instruction: "Émietter le thon, écraser à la fourchette avec un peu d'huile d'olive." },
      { numero: 3, instruction: "Garnir : thon, rondelles de tomate, anchois, olives, câpres. Décorer de basilic." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "tartine-houmous-legumes-grille-pain",
    titre: "Tartine houmous et légumes croquants",
    description: "Une tartine vegan colorée au houmous maison, carottes, concombre et radis. Healthy et instagrammable.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 3,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["GRILLE_PAIN"],
    categories: ["entree", "petit-dejeuner"],
    regime: ["vegan", "sans-lactose"],
    tags: ["houmous", "légumes", "vegan", "healthy"],
    calories_par_portion: 220,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Pain au levain", quantite: 4, unite: "tranche", categorie: "Boulangerie" },
      { nom: "Houmous", quantite: 200, unite: "g", categorie: "Épicerie" },
      { nom: "Carotte", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Concombre", quantite: 0.5, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Radis", quantite: 4, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Graines de sésame", quantite: 10, unite: "g", categorie: "Épicerie" },
      { nom: "Pousses (radis, alfalfa)", quantite: 30, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Huile d'olive", quantite: 10, unite: "ml", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Griller le pain au levain." },
      { numero: 2, instruction: "Tartiner généreusement de houmous." },
      { numero: 3, instruction: "Disposer carotte râpée, rondelles de concombre et de radis. Garnir de pousses, sésame et filet d'huile." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "tartine-oeuf-mimosa-grille-pain",
    titre: "Tartine œuf mimosa",
    description: "Une tartine généreuse à l'œuf dur écrasé en mayonnaise, ciboulette et toast croustillant.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 12,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["GRILLE_PAIN"],
    categories: ["entree", "petit-dejeuner"],
    regime: ["vegetarien"],
    tags: ["œuf", "mimosa", "ciboulette"],
    calories_par_portion: 240,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Pain de mie", quantite: 4, unite: "tranche", categorie: "Boulangerie" },
      { nom: "Œufs", quantite: 6, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Mayonnaise", quantite: 60, unite: "g", categorie: "Condiments" },
      { nom: "Moutarde", quantite: 10, unite: "g", categorie: "Condiments" },
      { nom: "Ciboulette", quantite: 10, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
      { nom: "Poivre", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Cuire les œufs durs (10 min eau bouillante). Refroidir, écaler.", duree: 600 },
      { numero: 2, instruction: "Écraser à la fourchette avec mayonnaise, moutarde, sel et poivre." },
      { numero: 3, instruction: "Griller le pain de mie. Garnir d'œuf mimosa, parsemer de ciboulette." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "tartine-ricotta-courgette-grille-pain",
    titre: "Tartine ricotta-courgette grillée",
    description: "Tartine légère à la ricotta crémeuse et courgette grillée parfumée à la menthe.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 5,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["GRILLE_PAIN"],
    categories: ["entree", "aperitif"],
    regime: ["vegetarien"],
    tags: ["ricotta", "courgette", "italien", "léger"],
    calories_par_portion: 190,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Pain ciabatta", quantite: 4, unite: "tranche", categorie: "Boulangerie" },
      { nom: "Ricotta", quantite: 200, unite: "g", categorie: "Produits laitiers" },
      { nom: "Courgette", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Menthe fraîche", quantite: 5, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Citron (zeste)", quantite: 0.5, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Huile d'olive", quantite: 15, unite: "ml", categorie: "Condiments" },
      { nom: "Poivre", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Trancher la courgette à la mandoline. Griller à la poêle 1 min par face avec un filet d'huile." },
      { numero: 2, instruction: "Griller les tranches de pain." },
      { numero: 3, instruction: "Tartiner de ricotta, ajouter les courgettes grillées, menthe ciselée, zeste de citron, poivre." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "tartine-camembert-pomme-grille-pain",
    titre: "Tartine camembert pomme et noix",
    description: "Mariage normand : camembert fondant, pomme acidulée et noix. Parfait avec une salade de roquette.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 5,
    temps_cuisson: 5,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["GRILLE_PAIN"],
    categories: ["entree", "aperitif"],
    regime: ["vegetarien"],
    tags: ["camembert", "pomme", "normand"],
    calories_par_portion: 270,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Pain de campagne", quantite: 4, unite: "tranche", categorie: "Boulangerie" },
      { nom: "Camembert", quantite: 200, unite: "g", categorie: "Produits laitiers" },
      { nom: "Pomme verte (Granny Smith)", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Noix", quantite: 40, unite: "g", categorie: "Épicerie" },
      { nom: "Miel", quantite: 20, unite: "g", categorie: "Épicerie" },
      { nom: "Roquette", quantite: 30, unite: "g", categorie: "Fruits & Légumes" },
    ],
    etapes: [
      { numero: 1, instruction: "Griller les tranches de pain au grille-pain." },
      { numero: 2, instruction: "Disposer des tranches de camembert. Passer 2 min au four à 200°C pour fondre.", duree: 120 },
      { numero: 3, instruction: "Ajouter rondelles de pomme, noix concassées, filet de miel et roquette." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  // ═══════════════════════════════════════════════════════════
  //                 MULTICUISEUR (10)
  // ═══════════════════════════════════════════════════════════

  {
    slug: "coq-au-vin-multicuiseur",
    titre: "Coq au vin traditionnel",
    description: "Le grand classique bourguignon : poulet mijoté au vin rouge avec lardons, oignons grelots et champignons.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 20,
    temps_cuisson: 60,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["MULTICUISEUR"],
    categories: ["plat"],
    regime: ["sans-gluten", "sans-lactose"],
    tags: ["coq au vin", "français", "bourguignon", "mijoté"],
    calories_par_portion: 480,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Cuisses de poulet", quantite: 6, unite: "pièce", categorie: "Viandes & Poissons" },
      { nom: "Vin rouge corsé", quantite: 500, unite: "ml", categorie: "Boissons" },
      { nom: "Lardons fumés", quantite: 150, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Oignons grelots", quantite: 200, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Champignons de Paris", quantite: 250, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Carottes", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Ail", quantite: 3, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Bouquet garni", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Concentré de tomate", quantite: 20, unite: "g", categorie: "Épicerie" },
      { nom: "Farine", quantite: 20, unite: "g", categorie: "Épicerie" },
      { nom: "Huile", quantite: 15, unite: "ml", categorie: "Épicerie" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mode Saisir : faire dorer les lardons et le poulet 8 min. Réserver le poulet." },
      { numero: 2, instruction: "Faire revenir oignons grelots et carottes en rondelles. Saupoudrer de farine, mélanger." },
      { numero: 3, instruction: "Remettre le poulet, ajouter ail, vin, concentré de tomate et bouquet garni. Programme Mijoter 50 min.", duree: 3000 },
      { numero: 4, instruction: "Ajouter les champignons 10 min avant la fin.", conseil: "Encore meilleur le lendemain. Servir avec des pâtes fraîches ou pommes vapeur." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "choucroute-alsacienne-multicuiseur",
    titre: "Choucroute garnie alsacienne",
    description: "La grande choucroute alsacienne avec saucisses, lard, jarret. Mijotage long pour des saveurs profondes.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 75,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["MULTICUISEUR"],
    categories: ["plat"],
    regime: ["sans-gluten", "sans-lactose"],
    tags: ["choucroute", "alsacien", "saucisses", "mijoté"],
    calories_par_portion: 580,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Choucroute crue", quantite: 1000, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Saucisses de Strasbourg", quantite: 4, unite: "pièce", categorie: "Viandes & Poissons" },
      { nom: "Saucisses de Montbéliard", quantite: 4, unite: "pièce", categorie: "Viandes & Poissons" },
      { nom: "Lard fumé", quantite: 300, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Jarret de porc", quantite: 1, unite: "pièce", categorie: "Viandes & Poissons" },
      { nom: "Vin blanc d'Alsace (Riesling)", quantite: 400, unite: "ml", categorie: "Boissons" },
      { nom: "Bouillon", quantite: 300, unite: "ml", categorie: "Épicerie" },
      { nom: "Oignons", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Baies de genièvre", quantite: 10, unite: "g", categorie: "Condiments" },
      { nom: "Feuilles de laurier", quantite: 2, unite: "pièce", categorie: "Condiments" },
      { nom: "Saindoux ou huile", quantite: 30, unite: "g", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Rincer la choucroute à l'eau froide, presser pour extraire l'eau. Émincer les oignons." },
      { numero: 2, instruction: "Mode Saisir : faire fondre le saindoux, faire suer les oignons. Ajouter la choucroute, le lard et le jarret." },
      { numero: 3, instruction: "Verser vin blanc et bouillon. Ajouter genièvre et laurier. Programme Mijoter 60 min.", duree: 3600 },
      { numero: 4, instruction: "Ajouter les saucisses 15 min avant la fin.", duree: 900, conseil: "Servir avec des pommes de terre vapeur." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "tajine-poulet-citron-multicuiseur",
    titre: "Tajine de poulet aux citrons confits",
    description: "Un tajine marocain parfumé aux épices et citrons confits. Le multicuiseur reproduit la cuisson lente du tajine.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 50,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["MULTICUISEUR"],
    categories: ["plat"],
    regime: ["sans-gluten", "sans-lactose"],
    tags: ["tajine", "marocain", "poulet", "citron confit"],
    calories_par_portion: 380,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Cuisses de poulet", quantite: 6, unite: "pièce", categorie: "Viandes & Poissons" },
      { nom: "Citrons confits", quantite: 2, unite: "pièce", categorie: "Condiments" },
      { nom: "Olives violettes", quantite: 100, unite: "g", categorie: "Épicerie" },
      { nom: "Oignon", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Ail", quantite: 4, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Gingembre frais", quantite: 15, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Cumin", quantite: 5, unite: "g", categorie: "Condiments" },
      { nom: "Curcuma", quantite: 5, unite: "g", categorie: "Condiments" },
      { nom: "Coriandre fraîche", quantite: 20, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Bouillon", quantite: 300, unite: "ml", categorie: "Épicerie" },
      { nom: "Huile d'olive", quantite: 30, unite: "ml", categorie: "Condiments" },
      { nom: "Safran", quantite: 0.2, unite: "g", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mode Saisir : dorer le poulet de tous côtés dans l'huile. Réserver." },
      { numero: 2, instruction: "Faire suer oignon émincé, ail et gingembre. Ajouter épices, faire revenir 1 min." },
      { numero: 3, instruction: "Remettre le poulet, ajouter citrons confits émincés, bouillon, safran. Programme Mijoter 45 min.", duree: 2700 },
      { numero: 4, instruction: "Ajouter olives 10 min avant la fin. Parsemer de coriandre.", conseil: "Servir avec semoule ou pain marocain." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "boudin-pommes-multicuiseur",
    titre: "Boudin noir aux pommes caramélisées",
    description: "Le boudin noir aux pommes, classique traditionnel français. Pommes fondantes et caramélisées.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 20,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["MULTICUISEUR"],
    categories: ["plat"],
    regime: ["sans-gluten", "sans-lactose"],
    tags: ["boudin noir", "pommes", "français", "automne"],
    calories_par_portion: 420,
    nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Boudin noir", quantite: 600, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Pommes (Reinette)", quantite: 4, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Oignon", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Beurre", quantite: 40, unite: "g", categorie: "Produits laitiers" },
      { nom: "Sucre roux", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Calvados (optionnel)", quantite: 30, unite: "ml", categorie: "Boissons" },
      { nom: "Cannelle", quantite: 1, unite: "pincée", categorie: "Condiments" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mode Saisir : faire fondre le beurre, ajouter l'oignon émincé. Suer 5 min." },
      { numero: 2, instruction: "Ajouter les pommes en quartiers et le sucre roux. Caraméliser 10 min.", duree: 600 },
      { numero: 3, instruction: "Pousser les pommes sur le côté. Faire dorer le boudin coupé en tronçons 5 min de chaque côté." },
      { numero: 4, instruction: "Flamber au calvados si utilisé. Saupoudrer de cannelle.", conseil: "Servir avec une purée de pommes de terre." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "confiture-abricots-multicuiseur",
    titre: "Confiture d'abricots à la vanille",
    description: "Une confiture d'abricots parfumée à la vanille, programme dédié du multicuiseur. Conservation 1 an.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 60,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["MULTICUISEUR"],
    categories: ["dessert", "petit-dejeuner"],
    regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["confiture", "abricot", "vanille", "été"],
    calories_par_portion: 200,
    nutriscore: "C",
    nutriscore_note: "Riche en sucre",
    ingredients: [
      { nom: "Abricots mûrs", quantite: 1000, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Sucre cristallisé", quantite: 700, unite: "g", categorie: "Épicerie" },
      { nom: "Gousse de vanille", quantite: 1, unite: "pièce", categorie: "Épicerie" },
      { nom: "Jus de citron", quantite: 30, unite: "ml", categorie: "Fruits & Légumes" },
    ],
    etapes: [
      { numero: 1, instruction: "Dénoyauter les abricots et les couper en 4. Macérer avec le sucre, la vanille fendue et le citron 1h." },
      { numero: 2, instruction: "Mettre dans le multicuiseur. Programme Confiture (45-60 min selon modèle).", duree: 3600 },
      { numero: 3, instruction: "Vérifier la prise sur une assiette froide : la goutte ne doit pas couler. Verser dans des pots stérilisés.", conseil: "Retourner les pots remplis à chaud pour faire le vide." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "yaourts-multicuiseur",
    titre: "Yaourts maison en multicuiseur",
    description: "8 yaourts onctueux préparés en mode \"Yaourt\" du multicuiseur. Plus économique que les yaourts du commerce.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 480,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["MULTICUISEUR"],
    categories: ["dessert", "petit-dejeuner"],
    regime: ["vegetarien", "sans-gluten"],
    tags: ["yaourt", "fait maison", "économique"],
    calories_par_portion: 110,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Lait entier", quantite: 1000, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Yaourt nature ferment", quantite: 1, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Lait en poudre", quantite: 30, unite: "g", categorie: "Produits laitiers" },
      { nom: "Sucre vanillé (optionnel)", quantite: 8, unite: "g", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Mélanger lait, lait en poudre, yaourt et sucre vanillé. Bien fouetter." },
      { numero: 2, instruction: "Remplir 8 pots à yaourt." },
      { numero: 3, instruction: "Disposer dans la cuve sans couvercle. Programme Yaourt 8h.", duree: 28800 },
      { numero: 4, instruction: "Refermer, réfrigérer 4h.", duree: 14400 },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "cheesecake-vapeur-multicuiseur",
    titre: "Cheesecake vapeur new-yorkais",
    description: "Le cheesecake américain ultra crémeux cuit à la vapeur du multicuiseur. Texture parfaite garantie.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 20,
    temps_cuisson: 35,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["MULTICUISEUR"],
    categories: ["dessert"],
    regime: ["vegetarien"],
    tags: ["cheesecake", "new-york", "fromage frais"],
    calories_par_portion: 420,
    nutriscore: "D",
    nutriscore_note: "Riche en lipides et sucre",
    ingredients: [
      { nom: "Cream cheese (Philadelphia)", quantite: 600, unite: "g", categorie: "Produits laitiers" },
      { nom: "Sucre", quantite: 150, unite: "g", categorie: "Épicerie" },
      { nom: "Œufs", quantite: 3, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Crème liquide", quantite: 100, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Maïzena", quantite: 15, unite: "g", categorie: "Épicerie" },
      { nom: "Vanille", quantite: 5, unite: "ml", categorie: "Épicerie" },
      { nom: "Biscuits speculoos", quantite: 200, unite: "g", categorie: "Épicerie" },
      { nom: "Beurre fondu", quantite: 80, unite: "g", categorie: "Produits laitiers" },
    ],
    etapes: [
      { numero: 1, instruction: "Mixer les biscuits, mélanger avec le beurre fondu. Tasser au fond d'un moule à charnière adapté à la cuve." },
      { numero: 2, instruction: "Fouetter cream cheese et sucre. Ajouter œufs, crème, maïzena et vanille." },
      { numero: 3, instruction: "Verser dans le moule. Couvrir d'aluminium." },
      { numero: 4, instruction: "Mettre dans le panier vapeur du multicuiseur avec 500ml d'eau dans la cuve. Programme Vapeur 35 min.", duree: 2100 },
      { numero: 5, instruction: "Laisser refroidir, puis 4h au frigo avant de démouler.", duree: 14400 },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "dahl-lentilles-corail-multicuiseur",
    titre: "Dahl de lentilles corail au lait de coco",
    description: "Le dahl indien crémeux aux lentilles corail et lait de coco, parfumé au curry. Réconfortant et vegan.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 10,
    temps_cuisson: 25,
    difficulte: "facile",
    nombre_portions: 4,
    modele_thermomix: ["MULTICUISEUR"],
    categories: ["plat"],
    regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["dahl", "lentilles corail", "indien", "vegan"],
    calories_par_portion: 320,
    nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Lentilles corail", quantite: 300, unite: "g", categorie: "Épicerie" },
      { nom: "Lait de coco", quantite: 400, unite: "ml", categorie: "Épicerie" },
      { nom: "Bouillon de légumes", quantite: 500, unite: "ml", categorie: "Épicerie" },
      { nom: "Tomates concassées", quantite: 200, unite: "g", categorie: "Épicerie" },
      { nom: "Oignon", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Ail", quantite: 3, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Gingembre frais", quantite: 15, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Curry en poudre", quantite: 15, unite: "g", categorie: "Condiments" },
      { nom: "Curcuma", quantite: 5, unite: "g", categorie: "Condiments" },
      { nom: "Huile de coco", quantite: 20, unite: "ml", categorie: "Condiments" },
      { nom: "Coriandre fraîche", quantite: 15, unite: "g", categorie: "Fruits & Légumes" },
    ],
    etapes: [
      { numero: 1, instruction: "Mode Saisir : faire revenir oignon, ail, gingembre dans l'huile de coco." },
      { numero: 2, instruction: "Ajouter curry et curcuma, faire revenir 1 min. Ajouter tomates, lentilles rincées, lait de coco et bouillon." },
      { numero: 3, instruction: "Programme Mijoter 25 min.", duree: 1500, conseil: "Mélanger en fin de cuisson pour rendre crémeux. Servir avec riz basmati." },
      { numero: 4, instruction: "Parsemer de coriandre fraîche." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "veau-marengo-multicuiseur",
    titre: "Veau Marengo aux champignons",
    description: "Le sauté de veau Marengo de tradition, sauce tomatée aux champignons et olives. Tendre et parfumé.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 60,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["MULTICUISEUR"],
    categories: ["plat"],
    regime: ["sans-lactose"],
    tags: ["veau", "marengo", "français", "champignons"],
    calories_par_portion: 380,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Sauté de veau (épaule)", quantite: 800, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Champignons de Paris", quantite: 250, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Tomates concassées", quantite: 400, unite: "g", categorie: "Épicerie" },
      { nom: "Vin blanc sec", quantite: 200, unite: "ml", categorie: "Boissons" },
      { nom: "Bouillon de volaille", quantite: 200, unite: "ml", categorie: "Épicerie" },
      { nom: "Oignon", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Ail", quantite: 3, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Olives noires", quantite: 80, unite: "g", categorie: "Épicerie" },
      { nom: "Bouquet garni", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Farine", quantite: 20, unite: "g", categorie: "Épicerie" },
      { nom: "Huile d'olive", quantite: 30, unite: "ml", categorie: "Condiments" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mode Saisir : faire dorer le veau en cubes 8 min. Réserver." },
      { numero: 2, instruction: "Faire suer oignon et ail. Saupoudrer de farine, mélanger." },
      { numero: 3, instruction: "Remettre le veau, ajouter tomates, vin, bouillon, bouquet garni. Programme Mijoter 50 min.", duree: 3000 },
      { numero: 4, instruction: "Ajouter champignons et olives 15 min avant la fin.", duree: 900, conseil: "Servir avec des pâtes fraîches ou du riz." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },

  {
    slug: "risotto-fruits-mer-multicuiseur",
    titre: "Risotto aux fruits de mer",
    description: "Un risotto crémeux aux gambas, moules et calamars. Le multicuiseur cuit le riz à la perfection sans surveiller.",
    image_url: null,
    video_youtube_id: null,
    temps_preparation: 15,
    temps_cuisson: 25,
    difficulte: "moyen",
    nombre_portions: 4,
    modele_thermomix: ["MULTICUISEUR"],
    categories: ["plat"],
    regime: ["sans-gluten"],
    tags: ["risotto", "fruits de mer", "italien"],
    calories_par_portion: 420,
    nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Riz Arborio", quantite: 300, unite: "g", categorie: "Épicerie" },
      { nom: "Gambas décortiquées", quantite: 200, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Moules décoquillées", quantite: 200, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Calamars en anneaux", quantite: 200, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Vin blanc", quantite: 100, unite: "ml", categorie: "Boissons" },
      { nom: "Bouillon de poisson", quantite: 1000, unite: "ml", categorie: "Épicerie" },
      { nom: "Échalote", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Ail", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Beurre", quantite: 30, unite: "g", categorie: "Produits laitiers" },
      { nom: "Persil plat", quantite: 10, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Huile d'olive", quantite: 20, unite: "ml", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mode Saisir : faire revenir échalotes et ail dans l'huile. Ajouter le riz, nacrer 1 min." },
      { numero: 2, instruction: "Déglacer au vin blanc. Ajouter le bouillon chaud, fermer." },
      { numero: 3, instruction: "Programme Riz ou Risotto 18 min.", duree: 1080 },
      { numero: 4, instruction: "Mode Saisir 5 min : ajouter les calamars, puis gambas et moules à mi-cuisson.", duree: 300 },
      { numero: 5, instruction: "Hors feu, ajouter beurre et persil. Mélanger énergiquement.", conseil: "Servir immédiatement." },
    ],
    faq: null,
    approuve: true,
    publie: true,
    vues: 0,
  },
];
