import type { SeedRecette } from "./seed-data";

export const SEED_THERMOMIX: SeedRecette[] = [
  // ── EXPRESS ⚡ (≤20min) ──────────────────────
  {
    slug: "smoothie-mangue-coco-thermomix",
    titre: "Smoothie mangue-coco",
    description: "Un smoothie tropical onctueux et vitaminé. Le Thermomix broie la mangue surgelée en quelques secondes pour une texture glacée parfaite.",
    image_url: null, video_youtube_id: null,
    temps_preparation: 5, temps_cuisson: 0, difficulte: "facile", nombre_portions: 4,
    modele_thermomix: ["TM5", "TM6", "TM7"],
    categories: ["boisson"], regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["smoothie", "tropical", "express", "été"],
    calories_par_portion: 145, nutriscore: "A",
    nutriscore_note: "Estimation indicative basée sur les ingrédients",
    ingredients: [
      { nom: "Mangue surgelée", quantite: 300, unite: "g", categorie: "Surgelés" },
      { nom: "Lait de coco", quantite: 200, unite: "ml", categorie: "Épicerie" },
      { nom: "Banane", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Jus de citron vert", quantite: 15, unite: "ml", categorie: "Fruits & Légumes" },
      { nom: "Miel ou sirop d'agave", quantite: 15, unite: "ml", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre la mangue surgelée, la banane coupée en rondelles et le lait de coco dans le bol.", vitesse: 8, duree: 30 },
      { numero: 2, instruction: "Ajouter le jus de citron vert et le miel. Mixer jusqu'à obtenir une consistance lisse.", vitesse: 10, duree: 20, conseil: "Si trop épais, ajouter un peu d'eau." },
    ],
    faq: [{ question: "Peut-on utiliser de la mangue fraîche ?", reponse: "Oui, mais ajoutez quelques glaçons pour la texture glacée." }],
    approuve: true, publie: true, vues: 0,
  },
  {
    slug: "sauce-tomate-express-thermomix",
    titre: "Sauce tomate express à l'italienne",
    description: "Une sauce tomate parfumée prête en 15 minutes. Basilic frais, ail et huile d'olive — la base de la cuisine italienne sans effort.",
    image_url: null, video_youtube_id: null,
    temps_preparation: 5, temps_cuisson: 10, difficulte: "facile", nombre_portions: 4,
    modele_thermomix: ["TM5", "TM6", "TM7"],
    categories: ["sauce"], regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["sauce", "tomate", "italien", "express", "base"],
    calories_par_portion: 85, nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Tomates pelées en boîte", quantite: 400, unite: "g", categorie: "Épicerie" },
      { nom: "Oignon", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Gousse d'ail", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Huile d'olive", quantite: 20, unite: "ml", categorie: "Condiments" },
      { nom: "Basilic frais", quantite: 10, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Sucre", quantite: 5, unite: "g", categorie: "Épicerie" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
      { nom: "Poivre", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre l'oignon et l'ail dans le bol. Hacher.", vitesse: 5, duree: 5 },
      { numero: 2, instruction: "Ajouter l'huile d'olive et faire revenir.", vitesse: 1, temperature: 120, duree: 120 },
      { numero: 3, instruction: "Ajouter les tomates pelées, le sucre, le sel et le poivre. Cuire.", vitesse: 2, temperature: 100, duree: 480 },
      { numero: 4, instruction: "Ajouter le basilic frais et mixer brièvement.", vitesse: 6, duree: 10, conseil: "Laisser quelques morceaux pour la texture." },
    ],
    faq: null, approuve: true, publie: true, vues: 0,
  },
  {
    slug: "houmous-maison-thermomix",
    titre: "Houmous maison crémeux",
    description: "Un houmous ultra crémeux au tahini et citron. Le Thermomix obtient une texture soyeuse impossible à reproduire au mixeur classique.",
    image_url: null, video_youtube_id: null,
    temps_preparation: 10, temps_cuisson: 0, difficulte: "facile", nombre_portions: 4,
    modele_thermomix: ["TM5", "TM6", "TM7"],
    categories: ["aperitif", "entree"], regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["houmous", "pois chiches", "mezze", "express"],
    calories_par_portion: 195, nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Pois chiches en boîte (égouttés)", quantite: 400, unite: "g", categorie: "Épicerie" },
      { nom: "Tahini (purée de sésame)", quantite: 60, unite: "g", categorie: "Épicerie" },
      { nom: "Jus de citron", quantite: 40, unite: "ml", categorie: "Fruits & Légumes" },
      { nom: "Gousse d'ail", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Huile d'olive", quantite: 30, unite: "ml", categorie: "Condiments" },
      { nom: "Cumin moulu", quantite: 3, unite: "g", categorie: "Condiments" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
      { nom: "Eau glacée", quantite: 30, unite: "ml", categorie: "Autre" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre l'ail dans le bol et hacher finement.", vitesse: 7, duree: 5 },
      { numero: 2, instruction: "Ajouter les pois chiches égouttés, le tahini, le jus de citron, le cumin et le sel.", vitesse: 5, duree: 15 },
      { numero: 3, instruction: "Racler les parois, ajouter l'eau glacée et l'huile d'olive. Mixer à vitesse maximale.", vitesse: 10, duree: 60, conseil: "L'eau glacée est le secret d'un houmous ultra lisse." },
    ],
    faq: [{ question: "Comment conserver le houmous ?", reponse: "Au réfrigérateur dans un contenant hermétique, jusqu'à 5 jours." }],
    approuve: true, publie: true, vues: 0,
  },
  {
    slug: "compote-pommes-cannelle-thermomix",
    titre: "Compote de pommes à la cannelle",
    description: "Une compote maison sans sucre ajouté, parfumée à la cannelle. Idéale pour les enfants et les desserts légers.",
    image_url: null, video_youtube_id: null,
    temps_preparation: 10, temps_cuisson: 10, difficulte: "facile", nombre_portions: 4,
    modele_thermomix: ["TM5", "TM6", "TM7"],
    categories: ["dessert"], regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["compote", "pomme", "cannelle", "enfant", "express"],
    calories_par_portion: 95, nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Pommes", quantite: 600, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Cannelle moulue", quantite: 3, unite: "g", categorie: "Condiments" },
      { nom: "Eau", quantite: 50, unite: "ml", categorie: "Autre" },
      { nom: "Jus de citron", quantite: 10, unite: "ml", categorie: "Fruits & Légumes" },
    ],
    etapes: [
      { numero: 1, instruction: "Éplucher et couper les pommes en quartiers. Les mettre dans le bol avec l'eau.", vitesse: 4, duree: 5 },
      { numero: 2, instruction: "Cuire les pommes.", vitesse: 2, temperature: 100, duree: 600, accessoire: "spatule" },
      { numero: 3, instruction: "Ajouter la cannelle et le jus de citron. Mixer selon la texture souhaitée.", vitesse: 5, duree: 15, conseil: "Vitesse 3-4 pour une compote avec morceaux." },
    ],
    faq: null, approuve: true, publie: true, vues: 0,
  },
  {
    slug: "mayonnaise-maison-thermomix",
    titre: "Mayonnaise maison en 1 minute",
    description: "La vraie mayonnaise maison, onctueuse et sans conservateur. Le Thermomix émulsionne parfaitement en quelques secondes.",
    image_url: null, video_youtube_id: null,
    temps_preparation: 5, temps_cuisson: 0, difficulte: "facile", nombre_portions: 4,
    modele_thermomix: ["TM6", "TM7"],
    categories: ["sauce"], regime: ["sans-gluten"],
    tags: ["mayonnaise", "sauce", "express", "base"],
    calories_par_portion: 320, nutriscore: "D",
    nutriscore_note: "Riche en lipides",
    ingredients: [
      { nom: "Jaune d'œuf", quantite: 1, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Moutarde de Dijon", quantite: 10, unite: "g", categorie: "Condiments" },
      { nom: "Huile de tournesol", quantite: 200, unite: "ml", categorie: "Épicerie" },
      { nom: "Jus de citron", quantite: 10, unite: "ml", categorie: "Fruits & Légumes" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre le jaune d'œuf, la moutarde, le sel et le jus de citron dans le bol.", vitesse: 4, duree: 10 },
      { numero: 2, instruction: "Programmer vitesse 4 et verser l'huile en filet continu par le bouchon.", vitesse: 4, duree: 60, conseil: "Verser lentement pour une émulsion parfaite." },
    ],
    faq: [{ question: "Pourquoi ma mayonnaise est ratée ?", reponse: "Les ingrédients doivent être à température ambiante. L'huile doit être versée très lentement." }],
    approuve: true, publie: true, vues: 0,
  },
  {
    slug: "pesto-basilic-thermomix",
    titre: "Pesto au basilic frais",
    description: "Le vrai pesto alla genovese : basilic frais, pignons de pin, parmesan et huile d'olive vierge. Prêt en 5 minutes.",
    image_url: null, video_youtube_id: null,
    temps_preparation: 10, temps_cuisson: 0, difficulte: "facile", nombre_portions: 4,
    modele_thermomix: ["TM5", "TM6", "TM7"],
    categories: ["sauce"], regime: ["vegetarien", "sans-gluten"],
    tags: ["pesto", "basilic", "italien", "express"],
    calories_par_portion: 280, nutriscore: "C",
    nutriscore_note: "Riche en lipides sains",
    ingredients: [
      { nom: "Basilic frais", quantite: 50, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Parmesan râpé", quantite: 50, unite: "g", categorie: "Produits laitiers" },
      { nom: "Pignons de pin", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Gousse d'ail", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Huile d'olive vierge", quantite: 100, unite: "ml", categorie: "Condiments" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre le parmesan en morceaux dans le bol et râper.", vitesse: 10, duree: 10 },
      { numero: 2, instruction: "Ajouter l'ail, les pignons de pin et hacher.", vitesse: 7, duree: 5 },
      { numero: 3, instruction: "Ajouter le basilic et l'huile d'olive. Mixer en gardant une texture légèrement granuleuse.", vitesse: 6, duree: 15, conseil: "Ne pas trop mixer pour garder du caractère." },
    ],
    faq: null, approuve: true, publie: true, vues: 0,
  },
  {
    slug: "vinaigrette-universelle-thermomix",
    titre: "Vinaigrette universelle émulsionnée",
    description: "Une vinaigrette parfaitement émulsionnée grâce au Thermomix. Se conserve 2 semaines au frigo.",
    image_url: null, video_youtube_id: null,
    temps_preparation: 5, temps_cuisson: 0, difficulte: "facile", nombre_portions: 4,
    modele_thermomix: ["TM5", "TM6", "TM7"],
    categories: ["sauce"], regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["vinaigrette", "salade", "express", "base"],
    calories_par_portion: 170, nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Huile d'olive", quantite: 100, unite: "ml", categorie: "Condiments" },
      { nom: "Vinaigre de cidre", quantite: 30, unite: "ml", categorie: "Condiments" },
      { nom: "Moutarde de Dijon", quantite: 15, unite: "g", categorie: "Condiments" },
      { nom: "Miel", quantite: 10, unite: "g", categorie: "Épicerie" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
      { nom: "Poivre", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre tous les ingrédients dans le bol.", vitesse: 5, duree: 15 },
      { numero: 2, instruction: "Émulsionner à vitesse maximale.", vitesse: 10, duree: 20, conseil: "La vinaigrette reste émulsionnée grâce à la moutarde." },
    ],
    faq: null, approuve: true, publie: true, vues: 0,
  },
  // ── RAPIDE 🕒 (21-40min) ────────────────────
  {
    slug: "risotto-parmesan-thermomix",
    titre: "Risotto crémeux au parmesan",
    description: "Un risotto onctueux cuit sans surveillance. Le Thermomix touille à votre place pour un résultat restaurant à la maison.",
    image_url: null, video_youtube_id: null,
    temps_preparation: 5, temps_cuisson: 25, difficulte: "facile", nombre_portions: 4,
    modele_thermomix: ["TM5", "TM6", "TM7"],
    categories: ["plat"], regime: ["vegetarien"],
    tags: ["risotto", "parmesan", "italien", "rapide", "crémeux"],
    calories_par_portion: 420, nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Riz arborio", quantite: 300, unite: "g", categorie: "Épicerie" },
      { nom: "Oignon", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Bouillon de légumes chaud", quantite: 800, unite: "ml", categorie: "Épicerie" },
      { nom: "Vin blanc sec", quantite: 100, unite: "ml", categorie: "Boissons" },
      { nom: "Parmesan râpé", quantite: 80, unite: "g", categorie: "Produits laitiers" },
      { nom: "Beurre", quantite: 30, unite: "g", categorie: "Produits laitiers" },
      { nom: "Huile d'olive", quantite: 15, unite: "ml", categorie: "Condiments" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
      { nom: "Poivre", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Hacher l'oignon.", vitesse: 5, duree: 5 },
      { numero: 2, instruction: "Ajouter l'huile d'olive et faire revenir.", vitesse: 1, temperature: 120, duree: 180, accessoire: "spatule" },
      { numero: 3, instruction: "Ajouter le riz et nacrer.", vitesse: 1, temperature: 120, duree: 120, accessoire: "spatule" },
      { numero: 4, instruction: "Verser le vin blanc et laisser absorber.", vitesse: 1, temperature: 100, duree: 120, accessoire: "spatule" },
      { numero: 5, instruction: "Ajouter le bouillon chaud. Cuire en mode mijotage.", vitesse: 1, temperature: 98, duree: 1080, accessoire: "spatule", conseil: "Ne pas ouvrir le couvercle pendant la cuisson." },
      { numero: 6, instruction: "Ajouter le beurre et le parmesan. Mélanger doucement.", vitesse: 1, duree: 30, conseil: "La mantecatura donne le crémeux final." },
    ],
    faq: [{ question: "Quel riz utiliser ?", reponse: "Le riz arborio ou carnaroli sont idéaux pour le risotto. N'utilisez pas de riz basmati." }],
    approuve: true, publie: true, vues: 0,
  },
  {
    slug: "soupe-poireaux-pommes-de-terre-thermomix",
    titre: "Soupe poireaux pommes de terre",
    description: "Un classique réconfortant de la cuisine française. Le Thermomix cuit et mixe en un seul programme.",
    image_url: null, video_youtube_id: null,
    temps_preparation: 10, temps_cuisson: 25, difficulte: "facile", nombre_portions: 4,
    modele_thermomix: ["TM5", "TM6", "TM7"],
    categories: ["soupe", "entree"], regime: ["vegetarien", "sans-gluten"],
    tags: ["soupe", "poireau", "pomme de terre", "hiver", "rapide"],
    calories_par_portion: 165, nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Poireaux", quantite: 400, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Pommes de terre", quantite: 300, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Bouillon de légumes", quantite: 600, unite: "ml", categorie: "Épicerie" },
      { nom: "Crème fraîche", quantite: 50, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Beurre", quantite: 20, unite: "g", categorie: "Produits laitiers" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
      { nom: "Poivre", quantite: 1, unite: "pincée", categorie: "Condiments" },
      { nom: "Muscade", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Couper les poireaux en tronçons et les pommes de terre en morceaux. Mettre dans le bol.", vitesse: 5, duree: 5 },
      { numero: 2, instruction: "Ajouter le beurre et faire suer.", vitesse: 1, temperature: 100, duree: 180, accessoire: "spatule" },
      { numero: 3, instruction: "Verser le bouillon, saler, poivrer, ajouter la muscade. Cuire.", vitesse: 1, temperature: 100, duree: 1200 },
      { numero: 4, instruction: "Ajouter la crème et mixer progressivement.", vitesse: 5, duree: 30 },
      { numero: 5, instruction: "Ajuster à vitesse maximale pour un velouté lisse.", vitesse: 10, duree: 30 },
    ],
    faq: null, approuve: true, publie: true, vues: 0,
  },
  {
    slug: "curry-poulet-coco-thermomix",
    titre: "Curry de poulet au lait de coco",
    description: "Un curry doux et parfumé, le poulet reste tendre grâce à la cuisson douce du Thermomix. Un voyage en Asie en 30 minutes.",
    image_url: null, video_youtube_id: null,
    temps_preparation: 10, temps_cuisson: 25, difficulte: "facile", nombre_portions: 4,
    modele_thermomix: ["TM6", "TM7"],
    categories: ["plat"], regime: ["sans-gluten", "sans-lactose", "halal"],
    tags: ["curry", "poulet", "coco", "asiatique", "rapide"],
    calories_par_portion: 380, nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Blancs de poulet", quantite: 500, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Lait de coco", quantite: 400, unite: "ml", categorie: "Épicerie" },
      { nom: "Oignon", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Gousse d'ail", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Gingembre frais", quantite: 10, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Pâte de curry jaune", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Poivron rouge", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Coriandre fraîche", quantite: 10, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Huile de tournesol", quantite: 10, unite: "ml", categorie: "Épicerie" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre l'oignon, l'ail et le gingembre dans le bol. Hacher.", vitesse: 5, duree: 5 },
      { numero: 2, instruction: "Ajouter l'huile et faire revenir.", vitesse: 1, temperature: 120, duree: 180 },
      { numero: 3, instruction: "Ajouter la pâte de curry et mélanger.", vitesse: 2, temperature: 100, duree: 60 },
      { numero: 4, instruction: "Ajouter le poulet coupé en dés, le poivron en lanières et le lait de coco. Cuire.", vitesse: 1, temperature: 98, duree: 1200, accessoire: "spatule" },
      { numero: 5, instruction: "Parsemer de coriandre fraîche ciselée. Servir avec du riz basmati.", conseil: "Goûter et ajuster le sel avant de servir." },
    ],
    faq: null, approuve: true, publie: true, vues: 0,
  },
  {
    slug: "pates-carbonara-thermomix",
    titre: "Pâtes à la carbonara authentique",
    description: "La vraie carbonara italienne : guanciale, jaunes d'œufs, pecorino et poivre. Sans crème. Le Thermomix gère la sauce onctueuse.",
    image_url: null, video_youtube_id: null,
    temps_preparation: 10, temps_cuisson: 20, difficulte: "moyen", nombre_portions: 4,
    modele_thermomix: ["TM5", "TM6", "TM7"],
    categories: ["plat"], regime: [],
    tags: ["pâtes", "carbonara", "italien", "rapide"],
    calories_par_portion: 520, nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Spaghetti", quantite: 400, unite: "g", categorie: "Épicerie" },
      { nom: "Guanciale ou lardons", quantite: 150, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Jaunes d'œufs", quantite: 4, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Pecorino romano râpé", quantite: 80, unite: "g", categorie: "Produits laitiers" },
      { nom: "Poivre noir", quantite: 3, unite: "g", categorie: "Condiments" },
      { nom: "Eau", quantite: 1500, unite: "ml", categorie: "Autre" },
      { nom: "Sel", quantite: 10, unite: "g", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre l'eau et le sel dans le bol. Porter à ébullition.", vitesse: 1, temperature: 100, duree: 600 },
      { numero: 2, instruction: "Ajouter les spaghetti dans le panier cuisson. Cuire selon le temps indiqué sur le paquet.", vitesse: 1, temperature: 100, duree: 720, accessoire: "panier" },
      { numero: 3, instruction: "Pendant ce temps, mélanger les jaunes d'œufs avec le pecorino et le poivre dans un bol séparé.", conseil: "Hors Thermomix, à la main." },
      { numero: 4, instruction: "Vider l'eau, remettre les pâtes dans le bol avec le guanciale rissolé. Ajouter le mélange œuf-fromage hors feu.", vitesse: 1, duree: 30, conseil: "Le bol doit être tiède, pas chaud, sinon les œufs cuisent." },
    ],
    faq: [{ question: "Peut-on mettre de la crème ?", reponse: "Non ! La vraie carbonara n'a pas de crème. L'onctuosité vient de l'émulsion jaune d'œuf + pecorino." }],
    approuve: true, publie: true, vues: 0,
  },
  {
    slug: "gaspacho-andalou-thermomix",
    titre: "Gaspacho andalou glacé",
    description: "La soupe froide espagnole par excellence. Tomates mûres, concombre, poivron — une explosion de fraîcheur estivale.",
    image_url: null, video_youtube_id: null,
    temps_preparation: 15, temps_cuisson: 0, difficulte: "facile", nombre_portions: 4,
    modele_thermomix: ["TM5", "TM6", "TM7"],
    categories: ["soupe", "entree"], regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["gaspacho", "espagnol", "froid", "été", "rapide"],
    calories_par_portion: 110, nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Tomates bien mûres", quantite: 500, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Concombre", quantite: 150, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Poivron rouge", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Gousse d'ail", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Pain rassis", quantite: 50, unite: "g", categorie: "Boulangerie" },
      { nom: "Huile d'olive", quantite: 40, unite: "ml", categorie: "Condiments" },
      { nom: "Vinaigre de xérès", quantite: 20, unite: "ml", categorie: "Condiments" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre tous les légumes grossièrement coupés et le pain dans le bol.", vitesse: 6, duree: 15 },
      { numero: 2, instruction: "Ajouter l'huile, le vinaigre et le sel. Mixer à fond.", vitesse: 10, duree: 60 },
      { numero: 3, instruction: "Réfrigérer au moins 1h avant de servir.", conseil: "Servir avec des croûtons et un filet d'huile d'olive." },
    ],
    faq: null, approuve: true, publie: true, vues: 0,
  },
  {
    slug: "crepes-bretonnes-thermomix",
    titre: "Crêpes bretonnes moelleuses",
    description: "La pâte à crêpes parfaite sans grumeaux, grâce au Thermomix. Repos 30 min recommandé puis cuisson à la poêle.",
    image_url: null, video_youtube_id: null,
    temps_preparation: 5, temps_cuisson: 20, difficulte: "facile", nombre_portions: 4,
    modele_thermomix: ["TM5", "TM6", "TM7"],
    categories: ["dessert", "petit-dejeuner"], regime: ["vegetarien"],
    tags: ["crêpes", "breton", "goûter", "rapide"],
    calories_par_portion: 290, nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Farine", quantite: 250, unite: "g", categorie: "Épicerie" },
      { nom: "Œufs", quantite: 3, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Lait", quantite: 500, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Beurre fondu", quantite: 30, unite: "g", categorie: "Produits laitiers" },
      { nom: "Sucre", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
      { nom: "Extrait de vanille", quantite: 5, unite: "ml", categorie: "Épicerie" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre les œufs, le lait, le beurre fondu, le sucre, le sel et la vanille dans le bol.", vitesse: 4, duree: 10 },
      { numero: 2, instruction: "Ajouter la farine et mélanger jusqu'à obtenir une pâte lisse.", vitesse: 6, duree: 30, conseil: "Racler les parois si nécessaire." },
      { numero: 3, instruction: "Laisser reposer 30 minutes au frigo. Cuire les crêpes à la poêle beurrée.", conseil: "La pâte doit être fluide comme de la crème liquide." },
    ],
    faq: [{ question: "Peut-on faire des crêpes salées ?", reponse: "Oui, supprimez le sucre et la vanille, ajoutez un peu plus de sel." }],
    approuve: true, publie: true, vues: 0,
  },
  {
    slug: "dahl-lentilles-corail-thermomix",
    titre: "Dahl de lentilles corail",
    description: "Un dahl indien onctueux aux épices douces. Les lentilles corail fondent en 20 minutes dans le Thermomix.",
    image_url: null, video_youtube_id: null,
    temps_preparation: 10, temps_cuisson: 25, difficulte: "facile", nombre_portions: 4,
    modele_thermomix: ["TM5", "TM6", "TM7"],
    categories: ["plat"], regime: ["vegan", "sans-gluten", "sans-lactose"],
    tags: ["dahl", "lentilles", "indien", "vegan", "rapide"],
    calories_par_portion: 260, nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Lentilles corail", quantite: 250, unite: "g", categorie: "Épicerie" },
      { nom: "Oignon", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Gousse d'ail", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Gingembre frais", quantite: 10, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Lait de coco", quantite: 200, unite: "ml", categorie: "Épicerie" },
      { nom: "Tomates concassées", quantite: 200, unite: "g", categorie: "Épicerie" },
      { nom: "Curcuma", quantite: 5, unite: "g", categorie: "Condiments" },
      { nom: "Cumin moulu", quantite: 3, unite: "g", categorie: "Condiments" },
      { nom: "Coriandre moulue", quantite: 3, unite: "g", categorie: "Condiments" },
      { nom: "Eau", quantite: 400, unite: "ml", categorie: "Autre" },
      { nom: "Huile de coco", quantite: 15, unite: "ml", categorie: "Épicerie" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Hacher l'oignon, l'ail et le gingembre.", vitesse: 5, duree: 5 },
      { numero: 2, instruction: "Ajouter l'huile de coco et les épices. Faire revenir.", vitesse: 1, temperature: 120, duree: 180 },
      { numero: 3, instruction: "Ajouter les lentilles rincées, les tomates, le lait de coco et l'eau. Cuire.", vitesse: 1, temperature: 100, duree: 1200, accessoire: "spatule" },
      { numero: 4, instruction: "Écraser légèrement pour une texture crémeuse.", vitesse: 3, duree: 10, conseil: "Ne pas trop mixer, garder de la texture." },
    ],
    faq: null, approuve: true, publie: true, vues: 0,
  },
  // ── ÉQUILIBRÉE 🍲 (41-75min) ────────────────
  {
    slug: "gratin-dauphinois-thermomix",
    titre: "Gratin dauphinois traditionnel",
    description: "Le vrai gratin dauphinois : pommes de terre, crème et muscade. Le Thermomix tranche les pommes de terre à la perfection.",
    image_url: null, video_youtube_id: null,
    temps_preparation: 15, temps_cuisson: 45, difficulte: "facile", nombre_portions: 4,
    modele_thermomix: ["TM5", "TM6", "TM7"],
    categories: ["accompagnement", "plat"], regime: ["vegetarien", "sans-gluten"],
    tags: ["gratin", "pomme de terre", "dauphinois", "classique"],
    calories_par_portion: 380, nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Pommes de terre", quantite: 800, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Crème liquide entière", quantite: 400, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Lait", quantite: 200, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Gousse d'ail", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Muscade", quantite: 2, unite: "pincée", categorie: "Condiments" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
      { nom: "Poivre", quantite: 1, unite: "pincée", categorie: "Condiments" },
      { nom: "Beurre", quantite: 15, unite: "g", categorie: "Produits laitiers" },
    ],
    etapes: [
      { numero: 1, instruction: "Éplucher les pommes de terre et les trancher finement au Thermomix.", vitesse: 4, duree: 10, conseil: "Utiliser la vitesse 4 pour des tranches régulières de 3mm." },
      { numero: 2, instruction: "Dans le bol nettoyé, chauffer la crème, le lait, l'ail écrasé, la muscade, le sel et le poivre.", vitesse: 2, temperature: 90, duree: 300 },
      { numero: 3, instruction: "Beurrer un plat à gratin. Disposer les pommes de terre en couches. Verser la crème chaude.", conseil: "Préchauffer le four à 180°C." },
      { numero: 4, instruction: "Enfourner 45 minutes à 180°C jusqu'à ce que le dessus soit doré.", conseil: "Couvrir de papier alu les 30 premières minutes." },
    ],
    faq: [{ question: "Peut-on ajouter du fromage ?", reponse: "Le vrai dauphinois n'a pas de fromage, mais vous pouvez ajouter du gruyère pour un gratin savoyard." }],
    approuve: true, publie: true, vues: 0,
  },
  {
    slug: "cake-citron-pavot-thermomix",
    titre: "Cake au citron et graines de pavot",
    description: "Un cake moelleux au citron frais et graines de pavot. Le glaçage acidulé au citron apporte la touche finale.",
    image_url: null, video_youtube_id: null,
    temps_preparation: 15, temps_cuisson: 45, difficulte: "facile", nombre_portions: 4,
    modele_thermomix: ["TM5", "TM6", "TM7"],
    categories: ["dessert", "petit-dejeuner"], regime: ["vegetarien"],
    tags: ["cake", "citron", "pavot", "goûter"],
    calories_par_portion: 340, nutriscore: "C",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Farine", quantite: 200, unite: "g", categorie: "Épicerie" },
      { nom: "Sucre", quantite: 150, unite: "g", categorie: "Épicerie" },
      { nom: "Œufs", quantite: 3, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Beurre mou", quantite: 100, unite: "g", categorie: "Produits laitiers" },
      { nom: "Citron (zeste et jus)", quantite: 2, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Graines de pavot", quantite: 20, unite: "g", categorie: "Épicerie" },
      { nom: "Levure chimique", quantite: 8, unite: "g", categorie: "Épicerie" },
      { nom: "Yaourt nature", quantite: 100, unite: "g", categorie: "Produits laitiers" },
    ],
    etapes: [
      { numero: 1, instruction: "Préchauffer le four à 175°C. Zester les citrons dans le bol.", vitesse: 10, duree: 10 },
      { numero: 2, instruction: "Ajouter le sucre, le beurre mou et les œufs. Mélanger.", vitesse: 5, duree: 20 },
      { numero: 3, instruction: "Ajouter la farine, la levure, le yaourt, le jus de citron et les graines de pavot. Mélanger.", vitesse: 4, duree: 20, conseil: "Ne pas trop mélanger, juste incorporer." },
      { numero: 4, instruction: "Verser dans un moule à cake beurré. Enfourner 40-45 minutes.", conseil: "Vérifier la cuisson avec un couteau : il doit ressortir sec." },
    ],
    faq: null, approuve: true, publie: true, vues: 0,
  },
  {
    slug: "blanquette-veau-thermomix",
    titre: "Blanquette de veau à l'ancienne",
    description: "La blanquette de veau traditionnelle avec sa sauce blanche onctueuse. Le Thermomix assure une cuisson douce parfaite.",
    image_url: null, video_youtube_id: null,
    temps_preparation: 20, temps_cuisson: 55, difficulte: "moyen", nombre_portions: 4,
    modele_thermomix: ["TM6", "TM7"],
    categories: ["plat"], regime: ["sans-gluten"],
    tags: ["blanquette", "veau", "classique", "français"],
    calories_par_portion: 450, nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Épaule de veau", quantite: 600, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Carottes", quantite: 200, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Champignons de Paris", quantite: 200, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Oignon", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Bouillon de volaille", quantite: 500, unite: "ml", categorie: "Épicerie" },
      { nom: "Crème fraîche", quantite: 100, unite: "ml", categorie: "Produits laitiers" },
      { nom: "Jaune d'œuf", quantite: 2, unite: "pièce", categorie: "Produits laitiers" },
      { nom: "Beurre", quantite: 30, unite: "g", categorie: "Produits laitiers" },
      { nom: "Farine", quantite: 20, unite: "g", categorie: "Épicerie" },
      { nom: "Bouquet garni", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Jus de citron", quantite: 10, unite: "ml", categorie: "Fruits & Légumes" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
      { nom: "Poivre", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Couper le veau en cubes. Mettre dans le bol avec le bouillon, l'oignon coupé en 4 et le bouquet garni.", vitesse: 1, temperature: 100, duree: 2400, accessoire: "spatule" },
      { numero: 2, instruction: "Ajouter les carottes en rondelles et les champignons. Poursuivre la cuisson.", vitesse: 1, temperature: 100, duree: 900 },
      { numero: 3, instruction: "Retirer la viande et les légumes. Réserver. Garder le bouillon dans le bol.", conseil: "Utiliser le panier pour égoutter facilement." },
      { numero: 4, instruction: "Ajouter le beurre et la farine au bouillon. Cuire pour faire un roux.", vitesse: 3, temperature: 90, duree: 180 },
      { numero: 5, instruction: "Mélanger la crème et les jaunes d'œufs dans un bol. Ajouter au Thermomix hors chaleur avec le citron.", vitesse: 3, duree: 30, conseil: "Ajouter hors feu pour ne pas faire cuire les jaunes." },
      { numero: 6, instruction: "Remettre la viande et les légumes dans la sauce. Réchauffer doucement.", vitesse: 1, temperature: 70, duree: 120 },
    ],
    faq: null, approuve: true, publie: true, vues: 0,
  },
  // ── MIJOTÉE 🔥 (≥76min) ─────────────────────
  {
    slug: "pain-complet-thermomix",
    titre: "Pain complet maison",
    description: "Un pain complet croustillant à l'extérieur, moelleux à l'intérieur. Le Thermomix pétrit la pâte à la perfection.",
    image_url: null, video_youtube_id: null,
    temps_preparation: 15, temps_cuisson: 40, difficulte: "moyen", nombre_portions: 4,
    modele_thermomix: ["TM5", "TM6", "TM7"],
    categories: ["boulangerie"], regime: ["vegan"],
    tags: ["pain", "complet", "boulangerie", "fait maison"],
    calories_par_portion: 210, nutriscore: "A",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Farine complète T150", quantite: 300, unite: "g", categorie: "Épicerie" },
      { nom: "Farine T65", quantite: 200, unite: "g", categorie: "Épicerie" },
      { nom: "Eau tiède", quantite: 320, unite: "ml", categorie: "Autre" },
      { nom: "Levure boulangère sèche", quantite: 7, unite: "g", categorie: "Épicerie" },
      { nom: "Sel", quantite: 8, unite: "g", categorie: "Condiments" },
      { nom: "Miel", quantite: 10, unite: "g", categorie: "Épicerie" },
      { nom: "Huile d'olive", quantite: 15, unite: "ml", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Mettre l'eau tiède, la levure et le miel dans le bol. Mélanger et laisser activer 5 min.", vitesse: 2, duree: 30 },
      { numero: 2, instruction: "Ajouter les farines, le sel et l'huile. Pétrir.", vitesse: 6, duree: 120, conseil: "Le mode pétrissage du TM6/TM7 est idéal ici." },
      { numero: 3, instruction: "Former une boule. Laisser lever 45 minutes dans un saladier couvert d'un linge humide.", conseil: "La pâte doit doubler de volume." },
      { numero: 4, instruction: "Dégazer, façonner. Laisser lever 20 min. Enfourner à 220°C pendant 35-40 minutes.", conseil: "Placer un bol d'eau dans le four pour une croûte croustillante." },
    ],
    faq: [{ question: "Pourquoi mon pain est trop dense ?", reponse: "La levure était peut-être inactive. Vérifiez la date de péremption et la température de l'eau (37°C max)." }],
    approuve: true, publie: true, vues: 0,
  },
  {
    slug: "boeuf-bourguignon-thermomix",
    titre: "Bœuf bourguignon mijoté",
    description: "Le grand classique bourguignon, mijoté lentement pour une viande fondante. Le Thermomix gère la cuisson longue sans surveillance.",
    image_url: null, video_youtube_id: null,
    temps_preparation: 20, temps_cuisson: 90, difficulte: "moyen", nombre_portions: 4,
    modele_thermomix: ["TM6", "TM7"],
    categories: ["plat"], regime: [],
    tags: ["bœuf", "bourguignon", "mijoté", "français", "hiver"],
    calories_par_portion: 480, nutriscore: "B",
    nutriscore_note: "Estimation indicative",
    ingredients: [
      { nom: "Bœuf à braiser (paleron)", quantite: 800, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Vin rouge Bourgogne", quantite: 500, unite: "ml", categorie: "Boissons" },
      { nom: "Lardons fumés", quantite: 100, unite: "g", categorie: "Viandes & Poissons" },
      { nom: "Carottes", quantite: 200, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Oignons grelots", quantite: 200, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Champignons de Paris", quantite: 200, unite: "g", categorie: "Fruits & Légumes" },
      { nom: "Bouillon de bœuf", quantite: 200, unite: "ml", categorie: "Épicerie" },
      { nom: "Concentré de tomates", quantite: 30, unite: "g", categorie: "Épicerie" },
      { nom: "Farine", quantite: 20, unite: "g", categorie: "Épicerie" },
      { nom: "Bouquet garni", quantite: 1, unite: "pièce", categorie: "Fruits & Légumes" },
      { nom: "Huile d'olive", quantite: 20, unite: "ml", categorie: "Condiments" },
      { nom: "Sel", quantite: 1, unite: "pincée", categorie: "Condiments" },
      { nom: "Poivre", quantite: 1, unite: "pincée", categorie: "Condiments" },
    ],
    etapes: [
      { numero: 1, instruction: "Couper le bœuf en gros cubes. Fariner légèrement.", conseil: "Sécher la viande avec du papier absorbant avant de fariner." },
      { numero: 2, instruction: "Mettre l'huile dans le bol et faire dorer les lardons.", vitesse: 1, temperature: 120, duree: 180 },
      { numero: 3, instruction: "Ajouter la viande et saisir.", vitesse: 1, temperature: 120, duree: 300, accessoire: "spatule" },
      { numero: 4, instruction: "Ajouter les carottes en rondelles, les oignons, le concentré de tomates, le vin rouge, le bouillon et le bouquet garni.", vitesse: 1, temperature: 100, duree: 4800, accessoire: "spatule", conseil: "Cuisson longue : 80 minutes de mijotage." },
      { numero: 5, instruction: "Ajouter les champignons 15 minutes avant la fin.", vitesse: 1, temperature: 100, duree: 900, accessoire: "spatule" },
    ],
    faq: null, approuve: true, publie: true, vues: 0,
  },
];
